"use client";
import { FormEvent, useEffect, useState } from "react";
import toast from "react-hot-toast";
import { adminService, type Brand } from "@/lib/api/endpoints/admin";

export default function AdminBrands() {
  const [rows,setRows]=useState<Brand[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [busy,setBusy]=useState(false);
  const load=async()=>{setLoading(true);setError("");try{setRows(await adminService.listBrands())}catch(e){setError(e instanceof Error?e.message:"Unable to load brands.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!name.trim()||!slug.trim())return;setBusy(true);try{await adminService.createBrand({name:name.trim(),slug:slug.trim()});setName("");setSlug("");toast.success("Brand created.");await load()}catch(cause){toast.error(cause instanceof Error?cause.message:"Unable to create brand.")}finally{setBusy(false)}};
  const remove=async(row:Brand)=>{if(!window.confirm(`Delete brand "${row.name}"?`))return;setBusy(true);try{await adminService.deleteBrand(row.id);toast.success("Brand deleted.");await load()}catch(cause){toast.error(cause instanceof Error?cause.message:"Unable to delete brand.")}finally{setBusy(false)}};
  return <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><form onSubmit={submit} className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Add brand</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="Brand name" className="mt-4 w-full rounded-xl border px-4 py-2.5"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="brand-slug" className="mt-3 w-full rounded-xl border px-4 py-2.5"/><button disabled={busy||!name.trim()||!slug.trim()} className="mt-4 w-full rounded-xl bg-gray-800 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Create brand</button><p className="mt-3 text-xs text-gray-500">Brand update and activation controls are unavailable because the backend currently supports create, list and delete only.</p></form><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex justify-between border-b p-5"><h3 className="font-semibold">Brands</h3><button onClick={()=>void load()} className="text-sm font-semibold text-orange-600">Refresh</button></div>{loading?<p className="p-10 text-center text-gray-500">Loading brands...</p>:error?<p className="p-10 text-center text-red-600">{error}</p>:!rows.length?<p className="p-10 text-center text-gray-500">No brands found.</p>:<table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Slug</th><th className="px-5 py-3">Created</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.id}><td className="px-5 py-4 font-semibold">{row.name}</td><td className="px-5 py-4 text-gray-500">{row.slug}</td><td className="px-5 py-4 text-gray-500">{new Date(row.created_at).toLocaleDateString()}</td><td className="px-5 py-4"><button disabled={busy} onClick={()=>void remove(row)} className="text-sm font-semibold text-red-600">Delete</button></td></tr>)}</tbody></table>}</section></div>;
}
