"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { BriefcaseBusiness,Edit3,FolderTree,Plus,RefreshCw,Search,Trash2,X } from "lucide-react";
import toast from "react-hot-toast";
import { adminService,type BusinessCategory,type ProductCategory } from "@/lib/api/endpoints/admin";
type Mode="product"|"business"; type Editing={type:"product";row:ProductCategory}|{type:"business";row:BusinessCategory}|null;
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
export default function AdminCategories(){
 const [mode,setMode]=useState<Mode>("product"),[products,setProducts]=useState<ProductCategory[]>([]),[businesses,setBusinesses]=useState<BusinessCategory[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[editing,setEditing]=useState<Editing>(null);
 const [pf,setPf]=useState({name:"",slug:"",parent_id:""}),[bf,setBf]=useState({name:"",slug:"",description:"",active:true});
 const load=async()=>{setLoading(true);setError("");try{const [a,b]=await Promise.all([adminService.listProductCategories(),adminService.listBusinessCategories()]);setProducts(a);setBusinesses(b)}catch(e){setError(e instanceof Error?e.message:"Unable to load categories.")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const pv=useMemo(()=>{const q=query.trim().toLowerCase();return products.filter(r=>`${r.name} ${r.slug}`.toLowerCase().includes(q))},[products,query]); const bv=useMemo(()=>{const q=query.trim().toLowerCase();return businesses.filter(r=>`${r.name} ${r.slug} ${r.description??""}`.toLowerCase().includes(q))},[businesses,query]);
 const createProduct=async(e:FormEvent)=>{e.preventDefault();if(!pf.name.trim())return;setBusy(true);try{await adminService.createProductCategory({name:pf.name.trim(),slug:pf.slug.trim()||slugify(pf.name),parent_id:pf.parent_id||null});setPf({name:"",slug:"",parent_id:""});toast.success("Product category created.");await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to create category.")}finally{setBusy(false)}};
 const createBusiness=async(e:FormEvent)=>{e.preventDefault();if(!bf.name.trim())return;setBusy(true);try{await adminService.createBusinessCategory({name:bf.name.trim(),slug:bf.slug.trim()||slugify(bf.name),description:bf.description.trim()||null,active:bf.active});setBf({name:"",slug:"",description:"",active:true});toast.success("Business category created.");await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to create business category.")}finally{setBusy(false)}};
 const save=async()=>{if(!editing)return;setBusy(true);try{if(editing.type==="product")await adminService.updateProductCategory(editing.row.id,{name:editing.row.name,slug:editing.row.slug,parent_id:editing.row.parent_id??null});else await adminService.updateBusinessCategory(editing.row.id,{name:editing.row.name,slug:editing.row.slug,description:editing.row.description,active:editing.row.active});toast.success("Category updated.");setEditing(null);await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to update category.")}finally{setBusy(false)}};
 const removeProduct=async(r:ProductCategory)=>{if(!confirm(`Delete category "${r.name}"?`))return;try{await adminService.deleteProductCategory(r.id);toast.success("Category deleted.");await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to delete category.")}}; const removeBusiness=async(r:BusinessCategory)=>{if(!confirm(`Delete business category "${r.name}"?`))return;try{await adminService.deleteBusinessCategory(r.id);toast.success("Business category deleted.");await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to delete business category.")}};
 const parent=(id?:string|null)=>id?products.find(r=>r.id===id)?.name||"Unknown":"—";
 return <div className="space-y-5"><section className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#f47524]">Catalog taxonomy</p><h2 className="mt-1 text-2xl font-bold">Category Management</h2><p className="mt-1 text-sm text-gray-500">Manage product categories and seller business categories with full CRUD operations.</p><div className="mt-5 inline-flex rounded-xl border bg-gray-50 p-1"><button onClick={()=>setMode("product")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${mode==="product"?"bg-white shadow":"text-gray-500"}`}>Product Categories ({products.length})</button><button onClick={()=>setMode("business")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${mode==="business"?"bg-white shadow":"text-gray-500"}`}>Business Categories ({businesses.length})</button></div></section><div className="grid gap-5 xl:grid-cols-[390px_minmax(0,1fr)]">
 {mode==="product"?<form onSubmit={createProduct} className="h-fit rounded-2xl border-2 bg-[#f8fafc] p-5 shadow-sm"><Head icon={FolderTree} title="Add Product Category" sub="Used by sellers when listing products."/><Field label="Category name"><input value={pf.name} onChange={e=>setPf({...pf,name:e.target.value,slug:pf.slug||slugify(e.target.value)})} placeholder="e.g. Electronics" className="field"/></Field><Field label="Slug"><input value={pf.slug} onChange={e=>setPf({...pf,slug:slugify(e.target.value)})} className="field"/></Field><Field label="Parent category"><select value={pf.parent_id} onChange={e=>setPf({...pf,parent_id:e.target.value})} className="field"><option value="">No parent</option>{products.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><button disabled={busy||!pf.name.trim()} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#111827] py-3 text-sm font-semibold text-white"><Plus size={15}/>Add Product Category</button></form>:<form onSubmit={createBusiness} className="h-fit rounded-2xl border-2 bg-[#f8fafc] p-5 shadow-sm"><Head icon={BriefcaseBusiness} title="Add Business Category" sub="Used during seller registration."/><Field label="Category name"><input value={bf.name} onChange={e=>setBf({...bf,name:e.target.value,slug:bf.slug||slugify(e.target.value)})} placeholder="e.g. Health & Wellness" className="field"/></Field><Field label="Slug"><input value={bf.slug} onChange={e=>setBf({...bf,slug:slugify(e.target.value)})} className="field"/></Field><Field label="Description"><textarea rows={4} value={bf.description} onChange={e=>setBf({...bf,description:e.target.value})} className="field resize-none"/></Field><label className="mt-4 flex gap-3 rounded-xl border bg-white p-3"><input type="checkbox" checked={bf.active} onChange={e=>setBf({...bf,active:e.target.checked})}/><span className="text-sm font-semibold">Active</span></label><button disabled={busy||!bf.name.trim()} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#111827] py-3 text-sm font-semibold text-white"><Plus size={15}/>Add Business Category</button></form>}
 <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h3 className="font-bold">{mode==="product"?"Product Categories":"Business Categories"}</h3><p className="text-xs text-gray-500">Edit or delete existing records.</p></div><div className="flex gap-2"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search categories..." className="h-10 rounded-xl border pl-9 pr-3 text-sm"/></div><button onClick={()=>void load()} className="rounded-xl border p-2"><RefreshCw size={15}/></button></div></div>{loading?<p className="p-10 text-center">Loading...</p>:error?<p className="p-10 text-center text-red-600">{error}</p>:mode==="product"?<table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-gray-50"><tr>{["Name","Slug","Parent","Created","Actions"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{pv.map(r=><tr key={r.id}><td className="px-5 py-4 font-semibold">{r.name}</td><td className="px-5 py-4 text-gray-500">{r.slug}</td><td className="px-5 py-4 text-gray-500">{parent(r.parent_id)}</td><td className="px-5 py-4 text-gray-500">{new Date(r.created_at).toLocaleDateString()}</td><td className="px-5 py-4"><Actions edit={()=>setEditing({type:"product",row:{...r}})} remove={()=>void removeProduct(r)}/></td></tr>)}</tbody></table>:<table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-gray-50"><tr>{["Name","Slug","Description","Status","Actions"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{bv.map(r=><tr key={r.id}><td className="px-5 py-4 font-semibold">{r.name}</td><td className="px-5 py-4 text-gray-500">{r.slug}</td><td className="max-w-xs px-5 py-4 text-gray-500">{r.description||"—"}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${r.active?"bg-green-50 text-green-700":"bg-gray-100 text-gray-600"}`}>{r.active?"Active":"Inactive"}</span></td><td className="px-5 py-4"><Actions edit={()=>setEditing({type:"business",row:{...r}})} remove={()=>void removeBusiness(r)}/></td></tr>)}</tbody></table>}</section></div>
 {editing&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="flex justify-between"><h3 className="font-bold">Edit Category</h3><button onClick={()=>setEditing(null)}><X size={18}/></button></div><Field label="Name"><input value={editing.row.name} onChange={e=>setEditing({...editing,row:{...editing.row,name:e.target.value}} as Editing)} className="field"/></Field><Field label="Slug"><input value={editing.row.slug} onChange={e=>setEditing({...editing,row:{...editing.row,slug:e.target.value}} as Editing)} className="field"/></Field>{editing.type==="product"?<Field label="Parent category"><select value={editing.row.parent_id??""} onChange={e=>setEditing({type:"product",row:{...editing.row,parent_id:e.target.value||null}})} className="field"><option value="">No parent</option>{products.filter(r=>r.id!==editing.row.id).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>:<><Field label="Description"><textarea rows={4} value={editing.row.description??""} onChange={e=>setEditing({type:"business",row:{...editing.row,description:e.target.value}})} className="field resize-none"/></Field><label className="mt-4 flex gap-3 rounded-xl border p-3"><input type="checkbox" checked={editing.row.active} onChange={e=>setEditing({type:"business",row:{...editing.row,active:e.target.checked}})}/><span>Active</span></label></>}<button disabled={busy} onClick={()=>void save()} className="mt-5 w-full rounded-xl bg-[#111827] py-3 font-semibold text-white">Save Changes</button></div></div>}<style jsx global>{`.field{margin-top:.5rem;min-height:46px;width:100%;border-radius:.75rem;border:2px solid #d8e0e9;background:#fff;padding:.7rem .9rem;font-size:.875rem;outline:none}.field:focus{border-color:#f47524}`}</style></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-4 block"><span className="text-sm font-semibold text-[#334155]">{label}</span>{children}</label>}
function Head({icon:Icon,title,sub}:{icon:typeof FolderTree;title:string;sub:string}){return <div className="flex items-center gap-3"><span className="rounded-xl bg-orange-50 p-2 text-[#f47524]"><Icon size={18}/></span><div><h3 className="font-bold">{title}</h3><p className="text-xs text-gray-500">{sub}</p></div></div>}
function Actions({edit,remove}:{edit:()=>void;remove:()=>void}){return <div className="flex gap-3"><button onClick={edit} className="inline-flex items-center gap-1 text-xs font-semibold text-blue-600"><Edit3 size={13}/>Edit</button><button onClick={remove} className="inline-flex items-center gap-1 text-xs font-semibold text-red-600"><Trash2 size={13}/>Delete</button></div>}
