"use client";
import { FormEvent, useEffect, useState } from "react";
import toast from "react-hot-toast";
import { adminService, type ProductCategory } from "@/lib/api/endpoints/admin";

export default function AdminCategories() {
  const [rows,setRows]=useState<ProductCategory[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [parentId,setParentId]=useState(""); const [busy,setBusy]=useState(false);
  const load=async()=>{setLoading(true);setError("");try{setRows(await adminService.listProductCategories())}catch(e){setError(e instanceof Error?e.message:"Unable to load categories.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!name.trim()||!slug.trim())return;setBusy(true);try{await adminService.createProductCategory({name:name.trim(),slug:slug.trim(),parent_id:parentId||null});setName("");setSlug("");setParentId("");toast.success("Category created.");await load()}catch(cause){toast.error(cause instanceof Error?cause.message:"Unable to create category.")}finally{setBusy(false)}};
  const remove=async(row:ProductCategory)=>{if(!window.confirm(`Delete category "${row.name}"?`))return;setBusy(true);try{await adminService.deleteProductCategory(row.id);toast.success("Category deleted.");await load()}catch(cause){toast.error(cause instanceof Error?cause.message:"Unable to delete category.")}finally{setBusy(false)}};
  const parentName=(id:string|null|undefined)=>id?rows.find(row=>row.id===id)?.name||id:"—";
  return <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><form onSubmit={submit} className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">Add category</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="Category name" className="mt-4 w-full rounded-xl border px-4 py-2.5"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="category-slug" className="mt-3 w-full rounded-xl border px-4 py-2.5"/><select value={parentId} onChange={e=>setParentId(e.target.value)} className="mt-3 w-full rounded-xl border px-4 py-2.5"><option value="">No parent</option>{rows.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select><button disabled={busy||!name.trim()||!slug.trim()} className="mt-4 w-full rounded-xl bg-gray-800 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Create category</button><p className="mt-3 text-xs text-gray-500">Update, ordering and activation controls are unavailable in the current backend.</p></form><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex justify-between border-b p-5"><h3 className="font-semibold">Categories</h3><button onClick={()=>void load()} className="text-sm font-semibold text-orange-600">Refresh</button></div>{loading?<p className="p-10 text-center text-gray-500">Loading categories...</p>:error?<p className="p-10 text-center text-red-600">{error}</p>:!rows.length?<p className="p-10 text-center text-gray-500">No categories found.</p>:<table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Slug</th><th className="px-5 py-3">Parent</th><th className="px-5 py-3">Created</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.id}><td className="px-5 py-4 font-semibold">{row.name}</td><td className="px-5 py-4 text-gray-500">{row.slug}</td><td className="px-5 py-4 text-gray-500">{parentName(row.parent_id)}</td><td className="px-5 py-4 text-gray-500">{new Date(row.created_at).toLocaleDateString()}</td><td className="px-5 py-4"><button disabled={busy} onClick={()=>void remove(row)} className="text-sm font-semibold text-red-600">Delete</button></td></tr>)}</tbody></table>}</section></div>;
}
