"use client";

import { useEffect, useMemo, useState } from "react";
import { AccessPermission, AccessRole, AccessSession, AccessUser, listAccessPermissions, listAccessRoles, listAccessSessions, listAccessUsers, revokeAccessSession, updateAccessRolePermissions, updateAccessUser, updateUserRoles } from "@/lib/api/endpoints/admin";

export type UserManagementView = "users" | "roles" | "permissions" | "sessions";
const titles = { users: "Users", roles: "Roles", permissions: "Permissions", sessions: "Active Sessions" };
const pretty = (v:string) => v.replaceAll(":"," · ").replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase());

export default function AdminUserManagement({view}:{view:UserManagementView}) {
  const [users,setUsers]=useState<AccessUser[]>([]); const [roles,setRoles]=useState<AccessRole[]>([]); const [permissions,setPermissions]=useState<AccessPermission[]>([]); const [sessions,setSessions]=useState<AccessSession[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [query,setQuery]=useState(""); const [selectedUser,setSelectedUser]=useState<AccessUser|null>(null); const [selectedRole,setSelectedRole]=useState<AccessRole|null>(null); const [busy,setBusy]=useState(false);
  const load=async()=>{setLoading(true);setError("");try{if(view==="users")setUsers(await listAccessUsers());if(view==="roles")setRoles(await listAccessRoles());if(view==="permissions")setPermissions(await listAccessPermissions());if(view==="sessions")setSessions(await listAccessSessions());}catch(e){setError(e instanceof Error?e.message:"Unable to load access data");}finally{setLoading(false)}};
  useEffect(()=>{setSelectedUser(null);setSelectedRole(null);void load()},[view]);
  const rows=useMemo(()=>view==="users"?users.filter(u=>`${u.first_name} ${u.last_name} ${u.email} ${u.roles.join(" ")}`.toLowerCase().includes(query.toLowerCase())):view==="roles"?roles.filter(r=>r.name.toLowerCase().includes(query.toLowerCase())):view==="permissions"?permissions.filter(p=>`${p.code} ${p.description}`.toLowerCase().includes(query.toLowerCase())):sessions.filter(s=>`${s.user_name} ${s.email}`.toLowerCase().includes(query.toLowerCase())),[view,users,roles,permissions,sessions,query]);
  const saveUser=async(user:AccessUser,nextRoles:string[],status:string)=>{setBusy(true);setError("");try{await updateUserRoles(user.id,nextRoles);if(status!==user.status)await updateAccessUser(user.id,{status});setSelectedUser(null);await load()}catch(e){setError(e instanceof Error?e.message:"Could not update user access")}finally{setBusy(false)}};
  const saveRole=async(role:AccessRole,codes:string[])=>{setBusy(true);setError("");try{await updateAccessRolePermissions(role.id,codes);setSelectedRole(null);await load()}catch(e){setError(e instanceof Error?e.message:"Could not update role")}finally{setBusy(false)}};
  const revoke=async(session:AccessSession)=>{if(!confirm(`Revoke ${session.user_name}'s session?`))return;setBusy(true);try{await revokeAccessSession(session.id);await load()}catch(e){setError(e instanceof Error?e.message:"Could not revoke session")}finally{setBusy(false)}};
  const metrics=view==="users"?[["Total users",users.length],["Active",users.filter(u=>u.status==="active").length],["Admins",users.filter(u=>u.roles.some(r=>["admin","super_admin"].includes(r))).length],["Suspended",users.filter(u=>u.status==="suspended").length]]:view==="roles"?[["Roles",roles.length],["Assigned users",roles.reduce((s,r)=>s+r.users_count,0)],["Permission links",roles.reduce((s,r)=>s+r.permissions.length,0)],["Protected roles",roles.filter(r=>r.name==="super_admin").length]]:view==="permissions"?[["Permissions",permissions.length],["User access",permissions.filter(p=>p.code.includes("user")).length],["Commerce",permissions.filter(p=>/(product|order|payment|coupon)/.test(p.code)).length],["Communications",permissions.filter(p=>p.code.includes("communication")).length]]:[["Active sessions",sessions.length],["Users online",new Set(sessions.map(s=>s.user_id)).size],["Current account",sessions.filter(s=>s.is_current_user).length],["Expiring today",sessions.filter(s=>new Date(s.expires_at).getTime()-Date.now()<86400000).length]];
  return <div className="space-y-5"><section className="rounded-3xl bg-gradient-to-br from-[#111827] via-[#312e81] to-[#f47524] p-6 text-white shadow-lg sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/60">Access governance</p><h2 className="mt-2 text-3xl font-semibold">{titles[view]}</h2><p className="mt-2 max-w-2xl text-sm text-white/75">Control identity, least-privilege access and authenticated sessions with traceable administrator actions.</p></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([l,v])=><article key={l} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{l}</p><p className="mt-2 text-2xl font-semibold">{v}</p></article>)}</section>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex gap-3 border-b p-5"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${titles[view].toLowerCase()}`} className="min-w-0 flex-1 rounded-xl border px-4 py-2.5 text-sm outline-none focus:border-orange-400"/><button onClick={()=>void load()} className="rounded-xl border px-4 text-sm font-semibold">Refresh</button></div>{loading?<p className="p-10 text-center text-gray-500">Loading access data...</p>:rows.length===0?<p className="p-10 text-center text-gray-500">No matching records.</p>:view==="users"?<UsersTable rows={rows as AccessUser[]} onSelect={setSelectedUser}/>:view==="roles"?<RolesTable rows={rows as AccessRole[]} onSelect={setSelectedRole}/>:view==="permissions"?<PermissionsGrid rows={rows as AccessPermission[]}/>:<SessionsTable rows={rows as AccessSession[]} busy={busy} onRevoke={revoke}/>}</section>{selectedUser&&<UserDrawer user={selectedUser} roles={roles} loadRoles={async()=>setRoles(await listAccessRoles())} busy={busy} onClose={()=>setSelectedUser(null)} onSave={saveUser}/>} {selectedRole&&<RoleDrawer role={selectedRole} permissions={permissions} loadPermissions={async()=>setPermissions(await listAccessPermissions())} busy={busy} onClose={()=>setSelectedRole(null)} onSave={saveRole}/>}</div>;
}

function UsersTable({rows,onSelect}:{rows:AccessUser[];onSelect:(u:AccessUser)=>void}){return <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{["User","Roles","Direct permissions","Sessions","Status",""].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(u=><tr key={u.id} className="hover:bg-gray-50"><td className="px-5 py-4"><p className="font-semibold">{`${u.first_name||""} ${u.last_name||""}`.trim()||u.email}</p><p className="text-xs text-gray-500">{u.email}</p></td><td className="px-5 py-4">{u.roles.length?u.roles.map(pretty).join(", "):"No role"}</td><td className="px-5 py-4">{u.direct_permissions.length}</td><td className="px-5 py-4">{u.active_sessions}</td><td className="px-5 py-4"><Badge value={u.status}/></td><td className="px-5 py-4"><button onClick={()=>onSelect(u)} className="font-semibold text-orange-600">Manage access</button></td></tr>)}</tbody></table></div>}
function RolesTable({rows,onSelect}:{rows:AccessRole[];onSelect:(r:AccessRole)=>void}){return <div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">{rows.map(r=><article key={r.id} className="rounded-2xl border p-5"><div className="flex justify-between"><div><h3 className="font-semibold">{pretty(r.name)}</h3><p className="mt-1 text-xs text-gray-500">{r.description||"Access role"}</p></div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs text-blue-700">{r.users_count} users</span></div><p className="mt-5 text-2xl font-semibold">{r.permissions.length}</p><p className="text-xs text-gray-500">assigned permissions</p><button disabled={r.name==="super_admin"} onClick={()=>onSelect(r)} className="mt-4 font-semibold text-orange-600 disabled:text-gray-400">{r.name==="super_admin"?"Protected role":"Edit permissions"}</button></article>)}</div>}
function PermissionsGrid({rows}:{rows:AccessPermission[]}){const groups=rows.reduce<Record<string,AccessPermission[]>>((all,p)=>{const key=p.code.includes(":")?p.code.split(":")[0]:p.code.includes("_")?p.code.split("_").slice(-1)[0]:"general";(all[key]??=[]).push(p);return all},{});return <div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">{Object.entries(groups).map(([g,items])=><article key={g} className="rounded-2xl border p-4"><h3 className="font-semibold">{pretty(g)}</h3><div className="mt-3 space-y-2">{items.map(p=><div key={p.id} className="rounded-xl bg-gray-50 p-3"><p className="text-sm font-medium">{pretty(p.code)}</p><p className="mt-1 text-xs text-gray-500">{p.description||p.name}</p></div>)}</div></article>)}</div>}
function SessionsTable({rows,busy,onRevoke}:{rows:AccessSession[];busy:boolean;onRevoke:(s:AccessSession)=>void}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{["User","Started","Expires","Session",""].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(s=><tr key={s.id}><td className="px-5 py-4"><p className="font-semibold">{s.user_name}</p><p className="text-xs text-gray-500">{s.email}</p></td><td className="px-5 py-4">{new Date(s.created_at).toLocaleString()}</td><td className="px-5 py-4">{new Date(s.expires_at).toLocaleString()}</td><td className="px-5 py-4">{s.is_current_user?<Badge value="current"/>:<Badge value="active"/>}</td><td className="px-5 py-4"><button disabled={busy} onClick={()=>onRevoke(s)} className="font-semibold text-red-600 disabled:opacity-40">Revoke</button></td></tr>)}</tbody></table></div>}
function UserDrawer({user,roles,loadRoles,busy,onClose,onSave}:{user:AccessUser;roles:AccessRole[];loadRoles:()=>Promise<void>;busy:boolean;onClose:()=>void;onSave:(u:AccessUser,r:string[],s:string)=>void}){const[selected,setSelected]=useState(user.roles);const[status,setStatus]=useState(user.status);useEffect(()=>{if(!roles.length)void loadRoles()},[]);return <Drawer title="Manage user access" onClose={onClose}><p className="font-semibold">{user.email}</p><label className="mt-5 block text-sm font-medium">Account status<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-1.5 w-full rounded-xl border px-3 py-2.5">{["active","inactive","suspended","pending_verification"].map(s=><option key={s}>{s}</option>)}</select></label><div className="mt-5"><p className="text-sm font-medium">Roles</p><div className="mt-2 space-y-2">{roles.map(r=><label key={r.id} className="flex items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={selected.includes(r.name)} onChange={e=>setSelected(e.target.checked?[...selected,r.name]:selected.filter(x=>x!==r.name))}/><span><b>{pretty(r.name)}</b><small className="block text-gray-500">{r.permissions.length} permissions</small></span></label>)}</div></div><button disabled={busy} onClick={()=>onSave(user,selected,status)} className="mt-6 w-full rounded-xl bg-[#111827] py-3 font-semibold text-white disabled:opacity-50">{busy?"Saving...":"Save access changes"}</button></Drawer>}
function RoleDrawer({role,permissions,loadPermissions,busy,onClose,onSave}:{role:AccessRole;permissions:AccessPermission[];loadPermissions:()=>Promise<void>;busy:boolean;onClose:()=>void;onSave:(r:AccessRole,p:string[])=>void}){const[selected,setSelected]=useState(role.permissions);useEffect(()=>{if(!permissions.length)void loadPermissions()},[]);return <Drawer title={`Edit ${pretty(role.name)}`} onClose={onClose}><p className="text-sm text-gray-500">Choose the capabilities inherited by every user assigned to this role.</p><div className="mt-5 max-h-[65vh] space-y-2 overflow-y-auto">{permissions.map(p=><label key={p.id} className="flex items-start gap-3 rounded-xl border p-3"><input type="checkbox" className="mt-1" checked={selected.includes(p.code)} onChange={e=>setSelected(e.target.checked?[...selected,p.code]:selected.filter(x=>x!==p.code))}/><span><b className="text-sm">{pretty(p.code)}</b><small className="block text-gray-500">{p.description}</small></span></label>)}</div><button disabled={busy} onClick={()=>onSave(role,selected)} className="mt-5 w-full rounded-xl bg-[#111827] py-3 font-semibold text-white disabled:opacity-50">{busy?"Saving...":"Update role permissions"}</button></Drawer>}
function Drawer({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[80] flex justify-end bg-black/40" onClick={onClose}><aside onClick={e=>e.stopPropagation()} className="h-full w-full max-w-lg overflow-y-auto bg-white p-6"><div className="flex justify-between"><h3 className="text-xl font-semibold">{title}</h3><button onClick={onClose} className="text-2xl text-gray-400">×</button></div><div className="mt-6">{children}</div></aside></div>}
function Badge({value}:{value:string}){return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${["active","current"].includes(value)?"bg-green-50 text-green-700":value==="suspended"?"bg-red-50 text-red-700":"bg-gray-100 text-gray-600"}`}>{pretty(value)}</span>}
