"use client";

import { logisticsAdminApi } from "@/lib/api/endpoints/logistics-admin";
import type { CompanyProfilePayload, LogisticsAccount } from "@/types/api/logistics-admin";
import { HugeiconsIcon, type IconSvgElement, type HugeiconsIconProps } from "@hugeicons/react";
import { Building03Icon, CheckmarkCircle02Icon, Globe02Icon, Mail01Icon, Location01Icon, Call02Icon, RefreshCwIcon, FloppyDiskIcon, ShieldCheckIcon } from "@hugeicons/core-free-icons";
import { FormEvent, useCallback, useEffect, useState } from "react";
import LogisticsDocuments from "@/components/Logistics/Documents";
import { useSearchParams } from "next/navigation";

const message = (error: unknown) => error instanceof Error ? error.message : "The request could not be completed.";
const blank: CompanyProfilePayload = { name: "", legal_name: "", description: "", registration_number: "", tax_identification_number: "", license_number: "", logo_url: "", contact_name: "", contact_email: "", contact_phone: "", website_url: "", address_line1: "", address_line2: "", city: "", region: "", country: "Tanzania", postal_code: "" };

export default function LogisticsSettings() {
 const searchParams = useSearchParams();
 const [account, setAccount] = useState<LogisticsAccount | null>(null); const [form, setForm] = useState<CompanyProfilePayload>(blank);
 const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
 const load = useCallback(async () => { setLoading(true); setError(""); try { const value = await logisticsAdminApi.account(); setAccount(value); const company = value.company; setForm({ name: company.name, legal_name: company.legal_name || "", description: company.description || "", registration_number: company.registration_number || "", tax_identification_number: company.tax_identification_number || "", license_number: company.license_number || "", logo_url: company.logo_url || "", contact_name: company.contact_name || "", contact_email: company.contact_email || "", contact_phone: company.contact_phone || "", website_url: company.website_url || "", address_line1: company.address_line1 || "", address_line2: company.address_line2 || "", city: company.city || "", region: company.region || "", country: company.country || "Tanzania", postal_code: company.postal_code || "" }); } catch (err) { setError(message(err)); } finally { setLoading(false); } }, []);
 useEffect(() => { void load(); }, [load]);
 useEffect(() => {
 if (searchParams.get("section") !== "documents") return;
 const timer = window.setTimeout(() => {
 document.getElementById("documents")?.scrollIntoView({ behavior: "smooth", block: "start" });
 }, 250);
 return () => window.clearTimeout(timer);
 }, [searchParams]);
 const set = (key: keyof CompanyProfilePayload, value: string) => setForm((current) => ({ ...current, [key]: value }));
 const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const company = await logisticsAdminApi.updateCompany(form); setAccount((current) => current ? { ...current, company } : current); setSuccess("Company profile saved successfully."); } catch (err) { setError(message(err)); } finally { setSaving(false); } };
 const canManage = Boolean(account?.can_manage_profile);

 if (loading) return <div className="mx-auto grid max-w-5xl gap-4 md:grid-cols-2">{Array.from({ length: 4 }).map((_, i) => <div key={i} className="h-44 animate-pulse rounded-xl bg-muted dark:bg-muted" />)}</div>;
 return <div className="mx-auto max-w-5xl space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Company administration</p><h2 className="text-2xl font-bold text-foreground">Company settings</h2><p className="mt-1 text-sm text-muted-foreground">Maintain the legal, contact and operating-address details used across Xerin.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-border bg-card px-4 text-sm font-semibold dark:border-border dark:bg-muted"><HugeiconsIcon icon={RefreshCwIcon} size={16} />Reload</button></header>
 {account && <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Building03Icon} label="Company code" value={account.company.code} /><Summary icon={ShieldCheckIcon} label="Company status" value={account.company.status} /><Summary icon={Globe02Icon} label="Operating scope" value={account.company.scope} /><Summary icon={CheckmarkCircle02Icon} label="Your access" value={account.member_role.replaceAll("_", " ")} /></section>}
 {error && <p className="rounded-xl border border-red-light-4 bg-red-light-6 p-4 text-sm text-red-dark">{error}</p>}{success && <p className="rounded-xl border border-green-light-4 bg-green-light-6 p-4 text-sm text-emerald-800">{success}</p>}{!canManage && account && <p className="rounded-xl border border-yellow-light-2 bg-yellow-light-4 p-4 text-sm text-amber-900">Your account can view this profile, but editing requires profile-management permission.</p>}
 <LogisticsDocuments />
 <form onSubmit={submit} className="space-y-5"><Section title="Business identity" icon={Building03Icon}><div className="grid gap-4 sm:grid-cols-2"><Field label="Trading name" required value={form.name} set={(value) => set("name", value)} /><Field label="Legal company name" value={form.legal_name || ""} set={(value) => set("legal_name", value)} /><Field label="Registration number" value={form.registration_number || ""} set={(value) => set("registration_number", value)} /><Field label="Tax identification number" value={form.tax_identification_number || ""} set={(value) => set("tax_identification_number", value)} /><Field label="Operating licence number" value={form.license_number || ""} set={(value) => set("license_number", value)} /><Field label="Logo URL" type="url" value={form.logo_url || ""} set={(value) => set("logo_url", value)} /></div><label className="mt-4 block text-sm font-semibold">Company description<textarea disabled={!canManage} value={form.description || ""} onChange={(e) => set("description", e.target.value)} className="mt-1.5 min-h-28 w-full rounded-xl border border-border bg-transparent p-3 disabled:bg-muted dark:border-border dark:disabled:bg-slate-800" /></label></Section>
 <Section title="Primary contact" icon={Mail01Icon}><div className="grid gap-4 sm:grid-cols-2"><Field label="Contact person" value={form.contact_name || ""} set={(value) => set("contact_name", value)} /><Field label="Contact email" type="email" value={form.contact_email || ""} set={(value) => set("contact_email", value)} /><Field label="Contact phone" type="tel" value={form.contact_phone || ""} set={(value) => set("contact_phone", value)} /><Field label="Website" type="url" value={form.website_url || ""} set={(value) => set("website_url", value)} /></div><div className="mt-4 flex flex-wrap gap-2 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><HugeiconsIcon icon={Mail01Icon} size={14} />Used for operational notices</span><span className="inline-flex items-center gap-1"><HugeiconsIcon icon={Call02Icon} size={14} />Used for urgent delivery coordination</span></div></Section>
 <Section title="Operating address" icon={Location01Icon}><div className="grid gap-4 sm:grid-cols-2"><Field label="Address line 1" value={form.address_line1 || ""} set={(value) => set("address_line1", value)} /><Field label="Address line 2" value={form.address_line2 || ""} set={(value) => set("address_line2", value)} /><Field label="City" value={form.city || ""} set={(value) => set("city", value)} /><Field label="Region" value={form.region || ""} set={(value) => set("region", value)} /><Field label="Country" required value={form.country || ""} set={(value) => set("country", value)} /><Field label="Postal code" value={form.postal_code || ""} set={(value) => set("postal_code", value)} /></div></Section>
 <button disabled={!canManage || saving} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground disabled:opacity-50 sm:w-auto"><HugeiconsIcon icon={FloppyDiskIcon} size={18} />{saving ? "Saving…" : "Save company settings"}</button>
 </form>
 </div>;

 function Field({ label, value, set: change, type = "text", required = false }: { label: string; value: string; set: (value: string) => void; type?: string; required?: boolean }) { return <label className="block text-sm font-semibold">{label}<input disabled={!canManage} required={required} type={type} value={value} onChange={(e) => change(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-border bg-transparent px-3 disabled:bg-muted dark:border-border dark:disabled:bg-slate-800" /></label>; }
}

function Section({ title, icon: Icon, children }: { title: string; icon: IconSvgElement; children: React.ReactNode }) { return <section className="rounded-xl border border-border bg-card p-4 shadow-sm sm:p-6 dark:border-border dark:bg-muted"><h3 className="flex items-center gap-2 text-lg font-bold"><HugeiconsIcon icon={Icon} size={18} className="text-primary" />{title}</h3><div className="mt-5">{children}</div></section>; }
function Summary({ icon: Icon, label, value }: { icon: IconSvgElement; label: string; value: string }) { return <article className="rounded-xl border border-border bg-card p-4 dark:border-border dark:bg-muted"><HugeiconsIcon icon={Icon} size={18} className="text-primary" /><p className="mt-3 break-words font-bold capitalize">{value.replaceAll("_", " ")}</p><p className="text-xs text-muted-foreground">{label}</p></article>; }
