"use client";

import { logisticsPricingApi } from "@/lib/api/endpoints/logistics-pricing";
import type { CountryOption, LogisticsScope, PricingSettings, PricingStrategy, ShippingRate, ShippingRatePayload, ShippingRateType, ShippingService, ShippingServicePayload, ShippingZone, ShippingZonePayload } from "@/types/api/logistics-pricing";
import { AlertTriangle, Boxes, CircleDollarSign, Pencil, Plus, RefreshCw, Route, Settings2, Trash2, Truck, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Tab = "zones" | "services" | "rates" | "strategy";
const pretty = (value: string) => value.replaceAll("_", " ");
const message = (error: unknown) => error instanceof Error ? error.message : "The request could not be completed.";
const list = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);
const optionalNumber = (value: string) => value.trim() === "" ? null : Number(value);
const money = (value: number | string, currency: string) => new Intl.NumberFormat("en-TZ", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(value || 0));

export default function LogisticsPricing() {
  const [tab, setTab] = useState<Tab>("zones"); const [countries, setCountries] = useState<CountryOption[]>([]); const [zones, setZones] = useState<ShippingZone[]>([]); const [services, setServices] = useState<ShippingService[]>([]); const [rates, setRates] = useState<ShippingRate[]>([]); const [settings, setSettings] = useState<PricingSettings | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editor, setEditor] = useState<"zone" | "service" | "rate" | null>(null); const [editing, setEditing] = useState<ShippingZone | ShippingService | ShippingRate | null>(null);
  const [deactivateTarget, setDeactivateTarget] = useState<{ kind: "zone" | "service" | "rate"; id: string; label: string } | null>(null); const [deactivating, setDeactivating] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [c, z, s, r, p] = await Promise.all([logisticsPricingApi.countryOptions(), logisticsPricingApi.zones(), logisticsPricingApi.services(), logisticsPricingApi.rates(), logisticsPricingApi.settings()]); setCountries(c); setZones(z.results); setServices(s.results); setRates(r.results); setSettings(p); } catch (err) { setError(message(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const open = (kind: "zone" | "service" | "rate", value: ShippingZone | ShippingService | ShippingRate | null = null) => { setEditing(value); setEditor(kind); };
  const deactivate = async () => { if (!deactivateTarget) return; const { kind, id } = deactivateTarget; setDeactivating(true); try { if (kind === "zone") await logisticsPricingApi.deactivateZone(id); else if (kind === "service") await logisticsPricingApi.deactivateService(id); else await logisticsPricingApi.deactivateRate(id); setDeactivateTarget(null); await load(); } catch (err) { setError(message(err)); } finally { setDeactivating(false); } };
  const tabs: Array<{ id: Tab; label: string; icon: typeof Boxes; count?: number }> = [{ id: "zones", label: "Coverage zones", icon: Route, count: zones.length }, { id: "services", label: "Delivery services", icon: Truck, count: services.length }, { id: "rates", label: "Rates", icon: CircleDollarSign, count: rates.length }, { id: "strategy", label: "Multi-seller strategy", icon: Settings2 }];

  return <div className="mx-auto max-w-7xl space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-blue">Pricing engine</p><h2 className="text-2xl font-bold text-slate-900 dark:text-white">Zones, services & rates</h2><p className="mt-1 max-w-2xl text-sm text-slate-500">Configure where you deliver, which services customers can select, and how checkout calculates delivery fees.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold disabled:opacity-50 dark:border-slate-700 dark:bg-slate-800"><RefreshCw size={17} className={loading ? "animate-spin" : ""} />Refresh</button></header>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{tabs.map(({ id, label, icon: Icon, count }) => <button key={id} onClick={() => setTab(id)} className={`min-h-24 rounded-2xl border p-4 text-left transition ${tab === id ? "border-blue bg-blue text-white" : "border-slate-200 bg-white text-slate-700 hover:border-blue dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"}`}><Icon size={20} /><p className="mt-2 text-sm font-semibold">{label}</p>{count !== undefined && <p className={`mt-1 text-xs ${tab === id ? "text-blue-100" : "text-slate-500"}`}>{count} configured</p>}</button>)}</section>
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {loading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-48 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800" />)}</div> : <>
      {tab === "zones" && <Panel title="Coverage zones" description="A zone must cover the whole country or contain at least one region, city, district, ward, or postal code." add={() => open("zone")} addLabel="Add zone"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{zones.map((zone) => <Card key={zone.id} title={zone.name} active={zone.is_active} subtitle={`${zone.country} · ${pretty(zone.scope)}`} edit={() => open("zone", zone)} remove={() => setDeactivateTarget({ kind: "zone", id: zone.id, label: zone.name })}><p>{zone.covers_entire_country ? "Entire country" : [zone.regions, zone.cities, zone.districts, zone.wards, zone.postal_codes].flat().join(", ") || "No coverage entered"}</p><p className="mt-2 text-xs text-slate-500">{[zone.supports_domestic_delivery && "Domestic", zone.supports_cross_border_inbound && "Inbound", zone.supports_cross_border_outbound && "Outbound"].filter(Boolean).join(" · ") || "No route capability"}</p></Card>)}</div>{!zones.length && <Empty text="No coverage zones configured." />}</Panel>}
      {tab === "services" && <Panel title="Delivery services" description="Define delivery windows, tracking availability, and cash-on-delivery support." add={() => open("service")} addLabel="Add service"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => <Card key={service.id} title={service.name} active={service.is_active} subtitle={`${service.min_delivery_days}–${service.max_delivery_days} day(s) · ${pretty(service.scope)}`} edit={() => open("service", service)} remove={() => setDeactivateTarget({ kind: "service", id: service.id, label: service.name })}><p>{service.service_code || "No service code"} · {service.supports_tracking ? "Tracking" : "No tracking"} · {service.supports_cod ? "COD" : "Prepaid"}</p></Card>)}</div>{!services.length && <Empty text="No delivery services configured." />}</Panel>}
      {tab === "rates" && <Panel title="Shipping rates" description="Rates connect one active service with one coverage zone." add={() => open("rate")} addLabel="Add rate"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rates.map((rate) => <Card key={rate.id} title={`${rate.zone.name} · ${rate.method.name}`} active={rate.is_active} subtitle={pretty(rate.rate_type)} edit={() => open("rate", rate)} remove={() => setDeactivateTarget({ kind: "rate", id: rate.id, label: `${rate.zone.name} · ${rate.method.name}` })}><p>Base {money(rate.base_amount, rate.currency)}{Number(rate.amount_per_km) > 0 ? ` + ${money(rate.amount_per_km, rate.currency)}/km` : ""}{Number(rate.amount_per_kg) > 0 ? ` + ${money(rate.amount_per_kg, rate.currency)}/kg` : ""}</p></Card>)}</div>{!rates.length && <Empty text="No shipping rates configured." />}</Panel>}
      {tab === "strategy" && settings && <Strategy value={settings} saved={(next) => setSettings(next)} />}
    </>}
    {editor === "zone" && <ZoneEditor countries={countries} value={editing as ShippingZone | null} close={() => setEditor(null)} saved={() => { setEditor(null); void load(); }} />}{editor === "service" && <ServiceEditor value={editing as ShippingService | null} close={() => setEditor(null)} saved={() => { setEditor(null); void load(); }} />}{editor === "rate" && <RateEditor value={editing as ShippingRate | null} zones={zones.filter((z) => z.is_active)} services={services.filter((s) => s.is_active)} close={() => setEditor(null)} saved={() => { setEditor(null); void load(); }} />}
    {deactivateTarget && <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/60 sm:items-center sm:p-4"><div role="dialog" aria-modal="true" aria-labelledby="deactivate-pricing-title" className="w-full max-w-md rounded-t-2xl bg-white p-5 shadow-2xl dark:bg-slate-900 sm:rounded-2xl sm:p-6"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-700 dark:bg-amber-500/10"><AlertTriangle size={20} /></span><div><h3 id="deactivate-pricing-title" className="font-bold capitalize">Deactivate {deactivateTarget.kind}?</h3><p className="mt-1 text-sm leading-6 text-slate-500"><strong>{deactivateTarget.label}</strong> will no longer be selectable for new pricing decisions. Existing order history will be preserved.</p></div></div><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button disabled={deactivating} onClick={() => setDeactivateTarget(null)} className="min-h-11 rounded-xl border px-4 text-sm font-semibold">Keep active</button><button disabled={deactivating} onClick={() => void deactivate()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-amber-600 px-4 text-sm font-bold text-white disabled:opacity-50">{deactivating && <RefreshCw className="animate-spin" size={15} />}Deactivate</button></div></div></div>}
  </div>;
}

function Panel({ title, description, add, addLabel, children }: { title: string; description: string; add: () => void; addLabel: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5 dark:border-slate-700 dark:bg-slate-800"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-lg font-bold">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div><button onClick={add} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue px-4 text-sm font-semibold text-white"><Plus size={17} />{addLabel}</button></div>{children}</section>; }
function Card({ title, subtitle, active, edit, remove, children }: { title: string; subtitle: string; active: boolean; edit: () => void; remove: () => void; children: React.ReactNode }) { return <article className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h4 className="break-words font-bold">{title}</h4><p className="mt-1 text-xs capitalize text-slate-500">{subtitle}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[11px] font-semibold ${active ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{active ? "Active" : "Inactive"}</span></div><div className="mt-4 break-words text-sm text-slate-600 dark:text-slate-300">{children}</div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={edit} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border text-sm font-semibold"><Pencil size={15} />Edit</button><button onClick={remove} disabled={!active} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-red-200 text-sm font-semibold text-red-700 disabled:opacity-40"><Trash2 size={15} />Deactivate</button></div></article>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500 dark:border-slate-700">{text}</div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/60 sm:items-center sm:p-4" role="dialog" aria-modal="true"><div className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-t-2xl bg-white shadow-2xl sm:rounded-2xl dark:bg-slate-900"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><h3 className="text-lg font-bold">{title}</h3><button onClick={close} className="grid min-h-11 min-w-11 place-items-center rounded-xl bg-slate-100 dark:bg-slate-800"><X /></button></header><div className="p-4 sm:p-6">{children}</div></div></div>; }
const field = "mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-transparent px-3 text-sm dark:border-slate-600";

function ZoneEditor({ countries, value, close, saved }: { countries: CountryOption[]; value: ShippingZone | null; close: () => void; saved: () => void }) {
  const [form, setForm] = useState({ name: value?.name || "", country: value?.country || "Tanzania", scope: value?.scope || "local" as LogisticsScope, regions: value?.regions.join(", ") || "", cities: value?.cities.join(", ") || "", districts: value?.districts.join(", ") || "", wards: value?.wards.join(", ") || "", postal_codes: value?.postal_codes.join(", ") || "", covers_entire_country: value?.covers_entire_country || false, supports_domestic_delivery: value?.supports_domestic_delivery ?? true, supports_cross_border_inbound: value?.supports_cross_border_inbound ?? false, supports_cross_border_outbound: value?.supports_cross_border_outbound ?? false, is_active: value?.is_active ?? true }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); const payload: ShippingZonePayload = { ...form, regions: list(form.regions), cities: list(form.cities), districts: list(form.districts), wards: list(form.wards), postal_codes: list(form.postal_codes) }; if (!payload.covers_entire_country && ![payload.regions, payload.cities, payload.districts, payload.wards, payload.postal_codes].some((items) => items.length)) { setError("Enter at least one coverage area or select entire country."); return; } if (![payload.supports_domestic_delivery, payload.supports_cross_border_inbound, payload.supports_cross_border_outbound].some(Boolean)) { setError("Enable at least one delivery capability for this country."); return; } setBusy(true); setError(""); try { value ? await logisticsPricingApi.updateZone(value.id, payload) : await logisticsPricingApi.createZone(payload); saved(); } catch (err) { setError(message(err)); } finally { setBusy(false); } };
  return <Modal title={value ? "Edit coverage zone" : "Add coverage zone"} close={close}><form onSubmit={submit} className="space-y-4">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><Label text="Zone name"><input required minLength={2} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className={field} /></Label><Label text="Country"><select required value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })} className={field}><option value="">Select country</option>{countries.map((country) => <option key={country.code} value={country.name}>{country.name}</option>)}</select><span className="mt-1.5 block text-xs font-normal text-slate-500">Choose the country from the Xerin country list so routes match accurately.</span></Label></div><Label text="Delivery scope"><select value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value as LogisticsScope })} className={field}>{["local", "international", "both"].map((x) => <option key={x}>{x}</option>)}</select></Label><div className="rounded-xl border border-slate-200 p-4 dark:border-white/10"><p className="text-sm font-bold">Delivery capabilities in this country</p><p className="mt-1 text-xs text-slate-500">Tick only the directions your company really supports for this country. You may enable one, two, or all three.</p><div className="mt-3 grid gap-2"><Check label="Domestic delivery within this country" checked={form.supports_domestic_delivery} set={(checked) => setForm({ ...form, supports_domestic_delivery: checked })} /><Check label="Cross-border inbound · foreign country → this country" checked={form.supports_cross_border_inbound} set={(checked) => setForm({ ...form, supports_cross_border_inbound: checked })} /><Check label="Cross-border outbound · this country → foreign country" checked={form.supports_cross_border_outbound} set={(checked) => setForm({ ...form, supports_cross_border_outbound: checked })} /></div></div><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={form.covers_entire_country} onChange={(e) => setForm({ ...form, covers_entire_country: e.target.checked })} className="h-5 w-5 accent-blue" />Covers the entire country</label>{!form.covers_entire_country && <div className="grid gap-3 sm:grid-cols-2">{(["regions", "cities", "districts", "wards", "postal_codes"] as const).map((key) => <Label key={key} text={`${pretty(key)} (comma separated)`}><input value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={field} /></Label>)}</div>}<Save busy={busy} label={value ? "Save zone" : "Create zone"} /></form></Modal>;
}

function ServiceEditor({ value, close, saved }: { value: ShippingService | null; close: () => void; saved: () => void }) {
  const [form, setForm] = useState<ShippingServicePayload>({ name: value?.name || "", service_code: value?.service_code || "", description: value?.description || "", carrier_name: value?.carrier_name || "", scope: value?.scope || "local", supports_cod: value?.supports_cod || false, supports_tracking: value?.supports_tracking ?? true, min_delivery_days: value?.min_delivery_days ?? 1, max_delivery_days: value?.max_delivery_days ?? 7, is_active: value?.is_active ?? true }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); if (form.max_delivery_days < form.min_delivery_days) { setError("Maximum delivery days cannot be lower than minimum days."); return; } setBusy(true); setError(""); try { value ? await logisticsPricingApi.updateService(value.id, form) : await logisticsPricingApi.createService(form); saved(); } catch (err) { setError(message(err)); } finally { setBusy(false); } };
  return <Modal title={value ? "Edit delivery service" : "Add delivery service"} close={close}><form onSubmit={submit} className="space-y-4">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><Label text="Service name"><input required minLength={2} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className={field} /></Label><Label text="Service code"><input value={form.service_code || ""} onChange={(e) => setForm({ ...form, service_code: e.target.value })} className={field} /></Label><Label text="Minimum delivery days"><input required type="number" min={0} max={365} value={form.min_delivery_days} onChange={(e) => setForm({ ...form, min_delivery_days: Number(e.target.value) })} className={field} /></Label><Label text="Maximum delivery days"><input required type="number" min={0} max={365} value={form.max_delivery_days} onChange={(e) => setForm({ ...form, max_delivery_days: Number(e.target.value) })} className={field} /></Label></div><Label text="Scope"><select value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value as LogisticsScope })} className={field}>{["local", "international", "both"].map((x) => <option key={x}>{x}</option>)}</select></Label><Label text="Description"><textarea value={form.description || ""} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-300 bg-transparent p-3 text-sm" /></Label><div className="grid gap-2 sm:grid-cols-2"><Check label="Supports tracking" checked={form.supports_tracking} set={(checked) => setForm({ ...form, supports_tracking: checked })} /><Check label="Supports cash on delivery" checked={form.supports_cod} set={(checked) => setForm({ ...form, supports_cod: checked })} /></div><Save busy={busy} label={value ? "Save service" : "Create service"} /></form></Modal>;
}

function RateEditor({ value, zones, services, close, saved }: { value: ShippingRate | null; zones: ShippingZone[]; services: ShippingService[]; close: () => void; saved: () => void }) {
  const [form, setForm] = useState({ zone_id: value?.zone_id || zones[0]?.id || "", method_id: value?.method_id || services[0]?.id || "", rate_type: value?.rate_type || "flat" as ShippingRateType, currency: value?.currency || "TZS", base_amount: String(value?.base_amount ?? 0), amount_per_kg: String(value?.amount_per_kg ?? 0), amount_per_km: String(value?.amount_per_km ?? 0), minimum_fee: String(value?.minimum_fee ?? ""), maximum_fee: String(value?.maximum_fee ?? ""), max_distance_km: String(value?.max_distance_km ?? ""), free_shipping_threshold: String(value?.free_shipping_threshold ?? ""), min_weight_kg: String(value?.min_weight_kg ?? ""), max_weight_kg: String(value?.max_weight_kg ?? ""), is_active: value?.is_active ?? true }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); const payload: ShippingRatePayload = { zone_id: form.zone_id, method_id: form.method_id, rate_type: form.rate_type, currency: form.currency.toUpperCase(), base_amount: Number(form.base_amount), amount_per_kg: Number(form.amount_per_kg), amount_per_km: Number(form.amount_per_km), minimum_fee: optionalNumber(form.minimum_fee), maximum_fee: optionalNumber(form.maximum_fee), max_distance_km: optionalNumber(form.max_distance_km), free_shipping_threshold: optionalNumber(form.free_shipping_threshold), min_weight_kg: optionalNumber(form.min_weight_kg), max_weight_kg: optionalNumber(form.max_weight_kg), is_active: form.is_active }; if (!payload.zone_id || !payload.method_id) { setError("Create an active zone and service before adding a rate."); return; } setBusy(true); setError(""); try { value ? await logisticsPricingApi.updateRate(value.id, payload) : await logisticsPricingApi.createRate(payload); saved(); } catch (err) { setError(message(err)); } finally { setBusy(false); } };
  const numeric = ["base_amount", "amount_per_kg", "amount_per_km", "minimum_fee", "maximum_fee", "max_distance_km", "free_shipping_threshold", "min_weight_kg", "max_weight_kg"] as const;
  return <Modal title={value ? "Edit shipping rate" : "Add shipping rate"} close={close}><form onSubmit={submit} className="space-y-4">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><Label text="Coverage zone"><select required value={form.zone_id} onChange={(e) => setForm({ ...form, zone_id: e.target.value })} className={field}><option value="">Select zone</option>{zones.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Label><Label text="Delivery service"><select required value={form.method_id} onChange={(e) => setForm({ ...form, method_id: e.target.value })} className={field}><option value="">Select service</option>{services.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Label><Label text="Rate type"><select value={form.rate_type} onChange={(e) => setForm({ ...form, rate_type: e.target.value as ShippingRateType })} className={field}>{["flat", "weight_based", "free", "per_km", "base_plus_per_km", "provider_quote"].map((x) => <option key={x} value={x}>{pretty(x)}</option>)}</select></Label><Label text="Currency"><input required minLength={3} maxLength={10} value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value })} className={field} /></Label>{numeric.map((key) => <Label key={key} text={pretty(key)}><input type="number" min={0} step="0.01" value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={field} /></Label>)}</div><Save busy={busy} label={value ? "Save rate" : "Create rate"} /></form></Modal>;
}

function Strategy({ value, saved }: { value: PricingSettings; saved: (value: PricingSettings) => void }) { const [strategy, setStrategy] = useState<PricingStrategy>(value.multi_seller_pricing_strategy); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submit = async () => { setBusy(true); setError(""); try { saved(await logisticsPricingApi.updateSettings(strategy)); } catch (err) { setError(message(err)); } finally { setBusy(false); } }; return <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-6 dark:border-slate-700 dark:bg-slate-800"><h3 className="text-lg font-bold">Multi-seller pricing strategy</h3><p className="mt-1 max-w-2xl text-sm text-slate-500">Controls how checkout calculates one delivery charge when a customer buys from several sellers.</p>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 grid gap-3 md:grid-cols-2">{value.supported_strategies.map((item) => <label key={item} className={`cursor-pointer rounded-2xl border p-4 ${strategy === item ? "border-blue bg-blue/5" : "border-slate-200 dark:border-slate-700"}`}><input type="radio" name="strategy" value={item} checked={strategy === item} onChange={() => setStrategy(item)} className="accent-blue" /><span className="ml-2 font-bold capitalize">{pretty(item)}</span><p className="mt-2 text-sm text-slate-500">{item === "farthest_seller" ? "Charge using the farthest seller-to-customer route." : "Add each seller-to-customer delivery route together."}</p></label>)}</div><button onClick={() => void submit()} disabled={busy || strategy === value.multi_seller_pricing_strategy} className="mt-5 min-h-11 rounded-xl bg-blue px-5 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Saving…" : "Save strategy"}</button></section>; }
function Label({ text, children }: { text: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold capitalize">{text}{children}</label>; }
function Check({ label, checked, set }: { label: string; checked: boolean; set: (value: boolean) => void }) { return <label className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 px-3 text-sm font-semibold dark:border-slate-700"><input type="checkbox" checked={checked} onChange={(e) => set(e.target.checked)} className="h-5 w-5 accent-blue" />{label}</label>; }
function Save({ busy, label }: { busy: boolean; label: string }) { return <button disabled={busy} className="min-h-12 w-full rounded-xl bg-blue px-4 text-sm font-bold text-white disabled:opacity-50">{busy ? "Saving…" : label}</button>; }
