"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { brokersApi } from "@/lib/api/endpoints/brokers";
import type { BrokerPayoutAccount, BrokerPayoutRequest, BrokerWallet, BrokerWalletTransaction } from "@/types/api/broker";
import { formatCurrency } from "@/utils/currency";
import toast from "react-hot-toast";

const cash=(v:string|number,c:string)=>formatCurrency(Number(v||0),c);
export default function BrokerWalletPage(){
 const [wallet,setWallet]=useState<BrokerWallet|null>(null),[tx,setTx]=useState<BrokerWalletTransaction[]>([]),[accounts,setAccounts]=useState<BrokerPayoutAccount[]>([]),[payouts,setPayouts]=useState<BrokerPayoutRequest[]>([]),[busy,setBusy]=useState(false),[showAccount,setShowAccount]=useState(false);
 const load=async()=>{try{const [w,t,a,p]=await Promise.all([brokersApi.wallet(),brokersApi.walletTransactions({page:1,page_size:50}),brokersApi.payoutAccounts(),brokersApi.payouts({page:1,page_size:50})]);setWallet(w);setTx(t.results);setAccounts(a);setPayouts(p.results)}catch(e){toast.error(e instanceof Error?e.message:"Unable to load Broker wallet")}};
 useEffect(()=>{void load()},[]);
 const verified=useMemo(()=>accounts.filter(a=>a.is_active&&a.verification_status==="verified"),[accounts]);
 async function addAccount(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await brokersApi.createPayoutAccount({account_type:String(f.get("account_type")) as "mobile_money"|"bank",provider:String(f.get("provider")),account_name:String(f.get("account_name")),account_number:String(f.get("account_number")),currency:String(f.get("currency")||"TZS"),is_default:true});toast.success("Payout account submitted for verification");setShowAccount(false);await load()}catch(x){toast.error(x instanceof Error?x.message:"Unable to add payout account")}finally{setBusy(false)}}
 async function request(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await brokersApi.requestPayout({payout_account_id:String(f.get("payout_account_id")),amount:String(f.get("amount")),note:String(f.get("note")||"")});toast.success("Payout requested");e.currentTarget.reset();await load()}catch(x){toast.error(x instanceof Error?x.message:"Payout request failed")}finally{setBusy(false)}}
 const c=wallet?.currency||"TZS";
 return <div className="space-y-5 pb-20 md:pb-0">
  <section className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-widest text-orange-300">Broker Finance · B6</p><h1 className="mt-2 text-3xl font-black">Wallet & Payouts</h1><p className="mt-2 max-w-2xl text-sm text-white/65">Only commission released from escrow is withdrawable. Payout funds are reserved until Admin completes or rejects the request.</p></section>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Pending",wallet?.pending_balance||"0"],["Available",wallet?.available_balance||"0"],["Reserved",wallet?.reserved_balance||"0"],["Paid out",wallet?.paid_out_balance||"0"],["Reversed",wallet?.reversed_balance||"0"]].map(([l,v])=><article key={l} className="rounded-2xl border bg-white p-5"><p className="text-sm font-semibold text-slate-500">{l}</p><p className="mt-2 text-xl font-black">{cash(v,c)}</p></article>)}</div>
  {Number(wallet?.debt_balance||0)>0&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 font-semibold text-red-700">Outstanding wallet debt: {cash(wallet?.debt_balance||0,c)}. Payouts are blocked until this is cleared.</div>}
  <div className="grid gap-5 xl:grid-cols-2">
   <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-black">Payout accounts</h2><p className="text-sm text-slate-500">Mobile money or bank account must be verified by Admin.</p></div><button onClick={()=>setShowAccount(v=>!v)} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Add account</button></div>
    {showAccount&&<form onSubmit={addAccount} className="mt-4 grid gap-3 sm:grid-cols-2"><select name="account_type" className="rounded-xl border px-3 py-3"><option value="mobile_money">Mobile money</option><option value="bank">Bank</option></select><input name="provider" required placeholder="Provider e.g. M-Pesa / CRDB" className="rounded-xl border px-3 py-3"/><input name="account_name" required placeholder="Account name" className="rounded-xl border px-3 py-3"/><input name="account_number" required placeholder="Phone / account number" className="rounded-xl border px-3 py-3"/><input name="currency" defaultValue="TZS" className="rounded-xl border px-3 py-3"/><button disabled={busy} className="rounded-xl bg-orange-500 px-4 py-3 font-bold text-white">Save account</button></form>}
    <div className="mt-4 space-y-2">{accounts.length===0?<p className="text-sm text-slate-500">No payout account yet.</p>:accounts.map(a=><div key={a.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><div><p className="font-bold">{a.provider} · {a.account_number}</p><p className="text-xs text-slate-500">{a.account_name} · {a.account_type.replaceAll("_"," ")}</p></div><span className="h-fit rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{a.verification_status}</span></div>{a.verification_note&&<p className="mt-2 text-xs text-red-600">{a.verification_note}</p>}</div>)}</div>
   </section>
   <section className="rounded-2xl border bg-white p-5"><h2 className="font-black">Request withdrawal</h2><p className="text-sm text-slate-500">Available balance: {cash(wallet?.available_balance||0,c)}</p><form onSubmit={request} className="mt-4 space-y-3"><select name="payout_account_id" required className="w-full rounded-xl border px-3 py-3"><option value="">Select verified payout account</option>{verified.map(a=><option key={a.id} value={a.id}>{a.provider} · {a.account_number}</option>)}</select><input name="amount" type="number" min="1" step="0.01" required placeholder="Amount" className="w-full rounded-xl border px-3 py-3"/><textarea name="note" placeholder="Optional note" className="w-full rounded-xl border px-3 py-3"/><button disabled={busy||verified.length===0} className="w-full rounded-xl bg-orange-500 px-4 py-3 font-bold text-white disabled:opacity-50">Request payout</button></form></section>
  </div>
  <section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-black">Payout history</h2></div><div className="divide-y">{payouts.length===0?<p className="p-5 text-sm text-slate-500">No payouts yet.</p>:payouts.map(p=><div key={p.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">{cash(p.amount,p.currency)}</p><p className="text-xs text-slate-500">{new Date(p.requested_at).toLocaleString()}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{p.status}</span>{["pending","approved"].includes(p.status)&&<button onClick={async()=>{try{await brokersApi.cancelPayout(p.id);await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to cancel")}}} className="text-xs font-bold text-red-600">Cancel</button>}</div></div>)}</div></section>
  <section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-black">Wallet ledger</h2></div><div className="divide-y">{tx.length===0?<p className="p-5 text-sm text-slate-500">No wallet transactions yet.</p>:tx.map(t=><div key={t.id} className="flex items-center justify-between gap-3 p-4"><div><p className="font-bold">{t.transaction_type.replaceAll("_"," ")}</p><p className="text-xs text-slate-500">{t.description||t.reference}</p></div><div className="text-right"><p className="font-black">{cash(t.amount,t.currency)}</p><p className="text-xs text-slate-500">{new Date(t.created_at).toLocaleDateString()}</p></div></div>)}</div></section>
 </div>
}
