"use client";
import { useEffect, useState } from "react";
import { brokersApi } from "@/lib/api/endpoints/brokers";
import type { BrokerPayoutAccount, BrokerPayoutRequest } from "@/types/api/broker";
import { formatCurrency } from "@/utils/currency";
import toast from "react-hot-toast";

export default function AdminBrokerPayouts(){
 const [accounts,setAccounts]=useState<BrokerPayoutAccount[]>([]),[payouts,setPayouts]=useState<BrokerPayoutRequest[]>([]),[status,setStatus]=useState("");
 const load=async()=>{try{const [a,p]=await Promise.all([brokersApi.adminPayoutAccounts(),brokersApi.adminPayouts({page:1,page_size:100,...(status?{status}:{})})]);setAccounts(a);setPayouts(p.results)}catch(e){toast.error(e instanceof Error?e.message:"Unable to load Broker payouts")}};
 useEffect(()=>{void load()},[status]);
 async function verify(a:BrokerPayoutAccount,next:"verified"|"rejected"){const note=next==="rejected"?(window.prompt("Reason for rejection:")||""):undefined;if(next==="rejected"&&!note)return;try{await brokersApi.adminVerifyPayoutAccount(a.id,next,note);toast.success(`Account ${next}`);await load()}catch(e){toast.error(e instanceof Error?e.message:"Action failed")}}
 async function move(p:BrokerPayoutRequest,next:string){let reference:string|undefined; if(next==="completed") reference=window.prompt("Provider payout reference:")||undefined; const note=window.prompt("Admin note (optional):")||undefined;try{await brokersApi.adminUpdatePayout(p.id,{status:next,provider_reference:reference,note});toast.success(`Payout ${next}`);await load()}catch(e){toast.error(e instanceof Error?e.message:"Payout update failed")}}
 return <div className="mx-auto max-w-7xl space-y-5 px-4 py-8"><section className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-orange-300">Admin · Broker Finance</p><h1 className="mt-2 text-3xl font-black">Broker Wallet Payouts</h1><p className="mt-2 text-sm text-white/65">Verify Broker payout destinations and move withdrawal requests through controlled payout states.</p></section>
 <section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-black">Payout account verification</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Provider</th><th className="p-3">Account</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="border-t"><td className="p-3"><b>{a.provider}</b><div className="text-xs text-slate-500">{a.account_type.replaceAll("_"," ")}</div></td><td className="p-3">{a.account_name}<div className="text-xs text-slate-500">{a.account_number}</div></td><td className="p-3">{a.verification_status}</td><td className="p-3"><div className="flex gap-2">{a.verification_status!=="verified"&&<button onClick={()=>void verify(a,"verified")} className="font-bold text-emerald-600">Verify</button>}{a.verification_status!=="rejected"&&<button onClick={()=>void verify(a,"rejected")} className="font-bold text-red-600">Reject</button>}</div></td></tr>)}</tbody></table></div></section>
 <section className="rounded-2xl border bg-white"><div className="flex items-center justify-between gap-3 border-b p-4"><h2 className="font-black">Payout requests</h2><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-3 py-2"><option value="">All statuses</option>{["pending","approved","processing","completed","failed","rejected","cancelled"].map(s=><option key={s}>{s}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Broker</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Requested</th><th className="p-3">Action</th></tr></thead><tbody>{payouts.map(p=><tr key={p.id} className="border-t"><td className="p-3 font-mono text-xs">{p.broker_id.slice(0,8)}…</td><td className="p-3 font-bold">{formatCurrency(Number(p.amount),p.currency)}</td><td className="p-3">{p.status}</td><td className="p-3">{new Date(p.requested_at).toLocaleString()}</td><td className="p-3"><div className="flex flex-wrap gap-2">{p.status==="pending"&&<><button onClick={()=>void move(p,"approved")} className="font-bold text-emerald-600">Approve</button><button onClick={()=>void move(p,"rejected")} className="font-bold text-red-600">Reject</button></>}{p.status==="approved"&&<button onClick={()=>void move(p,"processing")} className="font-bold text-orange-600">Processing</button>}{p.status==="processing"&&<><button onClick={()=>void move(p,"completed")} className="font-bold text-emerald-600">Complete</button><button onClick={()=>void move(p,"failed")} className="font-bold text-red-600">Fail</button></>}</div></td></tr>)}</tbody></table></div></section></div>
}
