"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import toast from "react-hot-toast";
import {brokersApi} from "@/lib/api/endpoints/brokers";
import type {BrokerRiskEvent} from "@/types/api/broker";

export default function AdminBrokerSecurity(){
  const [rows,setRows]=useState<BrokerRiskEvent[]>([]); const [status,setStatus]=useState("open"); const [severity,setSeverity]=useState(""); const [busy,setBusy]=useState<string|null>(null);
  async function load(){try{const r=await brokersApi.adminRiskEvents({page:1,page_size:100,...(status?{status}:{}),...(severity?{severity}:{})});setRows(r.results)}catch(e){toast.error(e instanceof Error?e.message:"Unable to load Broker security events")}}
  useEffect(()=>{void load()},[status,severity]);
  async function resolve(row:BrokerRiskEvent){const note=window.prompt("Resolution note (optional):")||undefined;setBusy(row.id);try{await brokersApi.adminResolveRisk(row.id,note);toast.success("Risk event resolved");await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to resolve event")}finally{setBusy(null)}}
  async function freeze(row:BrokerRiskEvent, frozen:boolean){if(!row.broker_id)return;const reason=window.prompt(frozen?"Reason to freeze this Broker wallet:":"Reason to unfreeze this Broker wallet:")||"";if(!reason)return;setBusy(row.id);try{await brokersApi.adminFreezeWallet(row.broker_id,frozen,reason);toast.success(frozen?"Broker wallet frozen":"Broker wallet unfrozen")}catch(e){toast.error(e instanceof Error?e.message:"Wallet action failed")}finally{setBusy(null)}}
  return <div className="mx-auto max-w-7xl space-y-5 px-4 py-8">
    <section className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-orange-300">Admin · B8 Security</p><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="mt-2 text-3xl font-black">Broker Risk & Abuse Monitor</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Review self-referrals, related-account referrals, referral traffic abuse and blocked payout activity.</p></div><Link href="/admin/brokers" className="rounded-xl border border-white/30 px-4 py-2 text-sm font-bold">Back to Brokers</Link></div></section>
    <section className="rounded-2xl border bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row"><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">All statuses</option><option value="open">Open</option><option value="resolved">Resolved</option></select><select value={severity} onChange={e=>setSeverity(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">All severity</option>{["critical","high","warning","info"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>void load()} className="rounded-xl bg-orange-500 px-5 py-3 font-bold text-white">Refresh</button></div>
      <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-3">When</th><th className="p-3">Risk</th><th className="p-3">Severity</th><th className="p-3">Broker</th><th className="p-3">Details</th><th className="p-3">Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b align-top"><td className="p-3 whitespace-nowrap">{new Date(r.created_at).toLocaleString()}</td><td className="p-3 font-bold">{r.event_type.replaceAll("_"," ")}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold uppercase">{r.severity}</span></td><td className="p-3 font-mono text-xs">{r.broker_id||"—"}</td><td className="p-3 max-w-sm text-xs text-slate-600">{r.details?JSON.stringify(r.details):"—"}</td><td className="p-3"><div className="flex flex-wrap gap-2">{r.status==="open"&&<button disabled={busy===r.id} onClick={()=>void resolve(r)} className="font-bold text-emerald-700">Resolve</button>}{r.broker_id&&<><button disabled={busy===r.id} onClick={()=>void freeze(r,true)} className="font-bold text-red-700">Freeze wallet</button><button disabled={busy===r.id} onClick={()=>void freeze(r,false)} className="font-bold text-slate-700">Unfreeze</button></>}</div></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-6 text-center text-slate-500">No Broker risk events match this filter.</p>}</div>
    </section>
  </div>
}
