import axiosInstance from "../client";
import type { Broker, BrokerKycDocument, BrokerKycStatus, PaginatedBrokers, BrokerProduct, BrokerProductCreate, BrokerProductUpdate, BrokerOpportunity, BrokerOfferAcceptance, BrokerReferralLink } from "@/types/api/broker";
export const brokersApi = {
  me: async () => (await axiosInstance.get<Broker>("/brokers/me")).data,
  updateMe: async (payload: Partial<Pick<Broker,"country"|"region"|"city"|"nida_number">>) => (await axiosInstance.patch<Broker>("/brokers/me", payload)).data,
  kycStatus: async () => (await axiosInstance.get<BrokerKycStatus>("/brokers/kyc-status")).data,
  documents: async () => { const r=await axiosInstance.get<{results:BrokerKycDocument[]}>("/brokers/kyc-documents"); return r.data.results; },
  upload: async (document_type:string,file:File) => { const f=new FormData(); f.append("document_type",document_type); f.append("file",file); return (await axiosInstance.post<BrokerKycDocument>("/brokers/kyc-documents",f,{headers:{"Content-Type":"multipart/form-data"}})).data; },
  deleteDocument: async (id:string) => (await axiosInstance.delete(`/brokers/kyc-documents/${id}`)).data,
  submitKyc: async () => (await axiosInstance.post<Broker>("/brokers/submit-kyc")).data,
  adminList: async (params?:Record<string,string|number>) => (await axiosInstance.get<PaginatedBrokers>("/brokers/admin",{params})).data,
  adminDocuments: async (id:string) => (await axiosInstance.get<BrokerKycDocument[]>(`/brokers/admin/${id}/documents`)).data,
  startReview: async (id:string) => (await axiosInstance.post<Broker>(`/brokers/admin/${id}/start-review`)).data,
  approve: async (id:string,reason?:string) => (await axiosInstance.post<Broker>(`/brokers/admin/${id}/approve`,{reason:reason||null})).data,
  reject: async (id:string,reason:string) => (await axiosInstance.post<Broker>(`/brokers/admin/${id}/reject`,{reason})).data,
  suspend: async (id:string,reason:string) => (await axiosInstance.post<Broker>(`/brokers/admin/${id}/suspend`,{reason})).data,
  adminDocumentViewUrl: (brokerId:string,docId:string) => `/brokers/admin/${brokerId}/documents/${docId}/view`,
  products: async (params?:Record<string,string|number>) => (await axiosInstance.get<BrokerProduct[]>("/brokers/products",{params})).data,
  createProduct: async (payload:BrokerProductCreate) => (await axiosInstance.post<BrokerProduct>("/brokers/products",payload)).data,
  updateProduct: async (id:string,payload:BrokerProductUpdate) => (await axiosInstance.patch<BrokerProduct>(`/brokers/products/${id}`,payload)).data,
  uploadProductImages: async (id:string,files:File[]) => { const f=new FormData(); files.forEach(file=>f.append("files",file)); return (await axiosInstance.post(`/brokers/products/${id}/images`,f,{headers:{"Content-Type":"multipart/form-data"}})).data; },
  deleteProductImage: async (id:string,imageId:string) => (await axiosInstance.delete(`/brokers/products/${id}/images/${imageId}`)).data,
  publishProduct: async (id:string) => (await axiosInstance.post<BrokerProduct>(`/brokers/products/${id}/publish`)).data,
  archiveProduct: async (id:string) => (await axiosInstance.delete(`/brokers/products/${id}`)).data,
  opportunities: async (params?:Record<string,string|number>) => (await axiosInstance.get<BrokerOpportunity[]>("/brokers/opportunities",{params})).data,
  acceptedOpportunities: async () => (await axiosInstance.get<BrokerOpportunity[]>("/brokers/accepted-opportunities")).data,
  acceptOpportunity: async (id:string) => (await axiosInstance.post<BrokerOfferAcceptance>(`/brokers/opportunities/${id}/accept`)).data,
  stopOpportunity: async (id:string) => (await axiosInstance.delete(`/brokers/opportunities/${id}/accept`)).data,
  referralLink: async (id:string) => (await axiosInstance.get<BrokerReferralLink>(`/brokers/opportunities/${id}/referral`)).data,
};
