"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import toast from "react-hot-toast";
import { ordersApi } from "@/lib/api/endpoints/commerce";
import type { Order } from "@/types/api/commerce";
import { formatCurrency } from "@/lib/formatCurrency";

export default function OrderList({ status, title = "Orders", subtitle }: { view?: string; status?: string; title?: string; subtitle?: string }) {
  const [rows,setRows]=useState<Order[]>([]);const [total,setTotal]=useState<number|null>(null);const [page,setPage]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const pageSize=20;
  const load=async()=>{setLoading(true);setError("");try{const data=await ordersApi.adminList({page,page_size:pageSize,status:status||undefined});setRows(data.results);setTotal(data.total)}catch(cause){setRows([]);setTotal(null);setError(cause instanceof Error?cause.message:"Unable to load orders.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[page,status]);
  const update=async(order:Order)=>{const next=window.prompt("New status: pending, paid, processing, shipped, delivered, cancelled or refunded",order.status)?.trim();if(!next||next===order.status)return;try{await ordersApi.updateStatus(order.id,{status:next});toast.success("Order status updated.");await load()}catch(cause){toast.error(cause instanceof Error?cause.message:"Status update failed.")}};
  return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h3 className="text-lg font-semibold">{title}</h3>{subtitle&&<p className="text-sm text-gray-500">{subtitle}</p>}<p className="text-xs text-gray-400">{total===null?"Total unavailable":`${total} backend records`}</p></div><button onClick={()=>void load()} className="rounded-xl border px-4 py-2 text-sm font-semibold">Refresh</button></div>{loading?<p className="p-10 text-center text-gray-500">Loading orders...</p>:error?<div className="p-10 text-center"><p className="text-red-600">{error}</p><button onClick={()=>void load()} className="mt-3 font-semibold text-orange-600">Retry</button></div>:!rows.length?<p className="p-10 text-center text-gray-500">No orders found.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-gray-50"><tr>{["Order","Items","Total","Status","Created","Actions"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.id}><td className="px-5 py-4 font-semibold">{row.id.slice(0,8).toUpperCase()}</td><td className="px-5 py-4">{row.items.length}</td><td className="px-5 py-4">{formatCurrency(row.total,row.currency)}</td><td className="px-5 py-4 capitalize">{row.status.replaceAll("_"," ")}</td><td className="px-5 py-4 text-gray-500">{row.created_at?new Date(row.created_at).toLocaleString():"—"}</td><td className="px-5 py-4"><div className="flex gap-3"><Link href={`/admin/orders/${row.id}`} className="font-semibold text-orange-600">Details</Link><button onClick={()=>void update(row)} className="font-semibold text-gray-700">Update status</button></div></td></tr>)}</tbody></table></div>}<div className="flex justify-end gap-2 border-t p-4"><button disabled={page===1||loading} onClick={()=>setPage(v=>v-1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Previous</button><button disabled={loading||total!==null&&page*pageSize>=total} onClick={()=>setPage(v=>v+1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Next</button></div></section>;
}
