"use client";
import type { XerinExpressOption } from "@/types/api/commerce";
import PriceDisplay from "@/components/shared/PriceDisplay";
import { HugeiconsIcon } from "@hugeicons/react";
import { Clock01Icon, PackageCheckIcon, ZapIcon } from "@hugeicons/core-free-icons";
export default function XerinExpress({options,selected,onSelect,loading}:{options:XerinExpressOption[];selected:string;onSelect:(o:XerinExpressOption)=>void;loading:boolean}){
 if(loading) return <div className="rounded-xl bg-muted p-6 text-sm">Finding the best Xerin Express options…</div>;
 return <section className="rounded-xl bg-card p-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><HugeiconsIcon icon={ZapIcon} size={20}/></span><div><h3 className="font-bold text-foreground">Xerin Express</h3><p className="text-xs text-muted-foreground">Choose your delivery speed. Xerin automatically assigns the best eligible domestic partner.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{options.map(o=><button type="button" key={o.tier} onClick={()=>onSelect(o)} className={`rounded-xl p-4 text-left transition ${selected===o.rate_id?"bg-primary/10":"bg-muted hover:bg-muted/60"}`}><div className="flex items-center justify-between"><b className="flex items-center gap-2 text-foreground">{o.tier==="express"?<HugeiconsIcon icon={ZapIcon} size={17}/>:<HugeiconsIcon icon={PackageCheckIcon} size={17}/>} {o.label}</b><PriceDisplay amount={Number(o.delivery_amount)} sourceCurrency="TZS"/></div><p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><HugeiconsIcon icon={Clock01Icon} size={14}/> Delivery target within {o.promised_delivery_minutes<60?`${o.promised_delivery_minutes} min`:`${Math.ceil(o.promised_delivery_minutes/60)} hr`}</p><p className="mt-2 text-[11px] text-muted-foreground">Delivery partner is assigned automatically after your selection.</p></button>)}</div>{!options.length&&<p className="mt-4 rounded-xl bg-yellow-light-4 p-3 text-sm text-yellow-dark-2">No Xerin Express Standard or Express service currently qualifies for this route.</p>}</section>
}
