"use client";

import { Spinner } from "@/components/ui/Spinner";
import { useEffect, useMemo, useState } from "react";
import { HugeiconsIcon } from "@hugeicons/react";
import { Search01Icon, RefreshCwIcon, PackageIcon, CheckmarkCircle02Icon, Copy01Icon, Share08Icon } from "@hugeicons/core-free-icons";
import toast from "react-hot-toast";
import { brokersApi } from "@/lib/api/endpoints/brokers";
import type { BrokerOpportunity } from "@/types/api/broker";

function money(v:string|number,c="TZS"){const n=Number(v);return Number.isFinite(n)?`${c} ${n.toLocaleString()}`:`${c} 0`;}
export default function BrokerOpportunities(){
 const [rows,setRows]=useState<BrokerOpportunity[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(""); const [busy,setBusy]=useState<string|null>(null); const [tab,setTab]=useState<"available"|"accepted">("available");
 const load=async()=>{setLoading(true);try{setRows(tab==="accepted"?await brokersApi.acceptedOpportunities():await brokersApi.opportunities(search.trim()?{search:search.trim()}:undefined));}catch(e){toast.error(e instanceof Error?e.message:"Unable to load Broker opportunities");}finally{setLoading(false)}};
 useEffect(()=>{void load()},[tab]);
 const count=useMemo(()=>rows.length,[rows]);
 const accept=async(o:BrokerOpportunity)=>{setBusy(o.offer.id);try{await brokersApi.acceptOpportunity(o.offer.id);toast.success("Opportunity accepted. Your referral link is ready.");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to accept opportunity");}finally{setBusy(null)}};

 const share=async(o:BrokerOpportunity)=>{setBusy(o.offer.id);try{const r=await brokersApi.referralLink(o.offer.id);const url=`${window.location.origin}${r.share_path}`;await navigator.clipboard.writeText(url);toast.success(`Referral link copied · Code ${r.referral_code}`);}catch(e){toast.error(e instanceof Error?e.message:"Unable to create referral link");}finally{setBusy(null)}};
 const stop=async(o:BrokerOpportunity)=>{setBusy(o.offer.id);try{await brokersApi.stopOpportunity(o.offer.id);toast.success("Promotion stopped.");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to stop promotion");}finally{setBusy(null)}};
 return <div className="space-y-5"><section className="rounded-xl bg-carbon p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-primary-300">Broker marketplace</p><h1 className="mt-2 text-3xl font-black">Promotion Opportunities</h1><p className="mt-2 max-w-2xl text-sm text-white/65">Choose approved, in-stock seller products and accept campaigns with a clearly stated reward per successful attributed sale.</p></section>
 <section className="rounded-xl border bg-card p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2"><button onClick={()=>setTab("available")} className={`rounded-xl px-4 py-2 text-sm font-bold ${tab==="available"?" text-primary-foreground":"bg-muted"}`}>Available</button><button onClick={()=>setTab("accepted")} className={`rounded-xl px-4 py-2 text-sm font-bold ${tab==="accepted"?"bg-primary text-primary-foreground":"bg-muted"}`}>My Promotions</button></div><div className="flex gap-2"><div className="relative"><HugeiconsIcon icon={Search01Icon} size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load()} placeholder="Search products..." className="h-10 rounded-xl border pl-9 pr-3 text-sm"/></div><button onClick={()=>void load()} className="rounded-xl border p-2"><HugeiconsIcon icon={RefreshCwIcon} size={18}/></button></div></div><p className="mt-3 text-xs text-muted-foreground">{count} opportunity{count===1?"":"ies"}</p></section>
 {loading?<div className="rounded-xl border bg-card p-12 text-center"><Spinner className="mx-auto" /></div>:rows.length===0?<div className="rounded-xl border bg-card p-12 text-center"><HugeiconsIcon icon={PackageIcon} className="mx-auto text-muted-foreground" size={40}/><p className="mt-3 font-bold">No opportunities available</p><p className="mt-1 text-sm text-muted-foreground">Campaigns automatically disappear when stock runs out, the seller disables them, or their end date passes.</p></div>:<div className="grid gap-4 lg:grid-cols-2">{rows.map(o=><article key={o.offer.id} className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">{o.product.currency}</p><h2 className="mt-1 text-lg font-black">{o.product.name}</h2><p className="mt-1 text-xs text-muted-foreground">Stock available: {o.available_quantity}</p></div>{o.already_accepted&&<span className="flex items-center gap-1 rounded-full bg-green-light-6 px-3 py-1 text-xs font-bold text-green-dark"><HugeiconsIcon icon={CheckmarkCircle02Icon} size={14}/>Accepted</span>}</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-muted p-3"><p className="text-[10px] font-bold uppercase text-muted-foreground">Customer price</p><p className="mt-1 font-black">{money(o.product.sale_price||o.product.price,o.product.currency)}</p></div><div className="rounded-xl bg-primary/10 p-3"><p className="text-[10px] font-bold uppercase text-primary">Your reward / unit</p><p className="mt-1 font-black">{money(o.offer.estimated_reward_per_unit,o.product.currency)}</p></div></div><div className="mt-3 text-xs text-muted-foreground">Reward rule: <b>{o.offer.commission_type==="fixed"?money(o.offer.commission_value,o.product.currency):`${o.offer.commission_value}%`}</b>{o.offer.max_attributed_sales?` · Campaign cap ${o.offer.max_attributed_sales} sales`:""}</div>{o.already_accepted?<div className="mt-5 grid grid-cols-2 gap-2"><button disabled={busy===o.offer.id} onClick={()=>void share(o)} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground"><HugeiconsIcon icon={Copy01Icon} size={16}/>{busy===o.offer.id?"Working...":"Copy Referral Link"}</button><button disabled={busy===o.offer.id} onClick={()=>void stop(o)} className="rounded-xl border bg-card px-4 py-3 text-sm font-bold text-accent-foreground">Stop Promoting</button></div>:<button disabled={busy===o.offer.id} onClick={()=>void accept(o)} className="mt-5 w-full rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground">{busy===o.offer.id?"Working...":"Accept & Promote"}</button>}</article>)}</div>}
 </div>
}
