"use client";

import { API_BASE_URL } from "@/lib/api/endpoints";
import { END_TO_END_PROBES, RESPONSIVE_VIEWPORTS, type QaProbe, type QaRole } from "@/lib/qa/end-to-end-matrix";
import { useAuthStore } from "@/store/useAuthStore";
import { CheckCircle2, CircleAlert, ExternalLink, MonitorSmartphone, Play, RefreshCw, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

type ProbeResult = { id: string; status: number; outcome: "passed" | "protected" | "failed"; duration: number; detail: string };
const roles: QaRole[] = ["customer", "seller", "logistics", "admin"];
const pretty = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (x) => x.toUpperCase());

export default function EndToEndQa() {
  const token = useAuthStore((state) => state.accessToken); const user = useAuthStore((state) => state.user);
  const [results, setResults] = useState<Record<string, ProbeResult>>({}); const [running, setRunning] = useState(false); const [checked, setChecked] = useState<Record<string, boolean>>({});
  const runOne = async (probe: QaProbe): Promise<ProbeResult> => { const started = performance.now(); try { const response = await fetch(`${API_BASE_URL}${probe.endpoint}`, { method: probe.method, headers: { Accept: "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, cache: "no-store" }); const duration = Math.round(performance.now() - started); if (response.ok) return { id: probe.id, status: response.status, outcome: "passed", duration, detail: "Endpoint responded for the current session." }; if ([401, 403].includes(response.status)) return { id: probe.id, status: response.status, outcome: "protected", duration, detail: response.status === 403 ? "Reachable and protected from this role." : "Reachable; authentication is required." }; return { id: probe.id, status: response.status, outcome: "failed", duration, detail: response.status === 404 ? "Endpoint was not found." : `Backend returned HTTP ${response.status}.` }; } catch (error) { return { id: probe.id, status: 0, outcome: "failed", duration: Math.round(performance.now() - started), detail: error instanceof Error ? error.message : "Network request failed." }; } };
  const run = async () => { setRunning(true); setResults({}); const values = await Promise.all(END_TO_END_PROBES.map(runOne)); setResults(Object.fromEntries(values.map((value) => [value.id, value]))); setRunning(false); };
  const totals = useMemo(() => Object.values(results).reduce((sum, row) => ({ ...sum, [row.outcome]: sum[row.outcome] + 1 }), { passed: 0, protected: 0, failed: 0 }), [results]);
  const manualDone = Object.values(checked).filter(Boolean).length; const manualTotal = RESPONSIVE_VIEWPORTS.length * roles.length;
  return <div className="space-y-5"><section className="overflow-hidden rounded-2xl bg-gradient-to-br from-slate-950 via-slate-800 to-blue-600 p-5 text-white shadow-lg sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-200">Phase 5 · QA</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">End-to-end readiness runner</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/75">Run safe GET-only contract probes across customer, seller, logistics and administrator workflows. A protected result confirms the route exists but correctly rejects the current role.</p></div><button onClick={() => void run()} disabled={running || !token} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-bold text-slate-900 disabled:opacity-50">{running ? <RefreshCw className="animate-spin" size={18} /> : <Play size={18} />}{running ? "Running checks…" : "Run smoke suite"}</button></div></section>
    {!token && <p className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Sign in as an administrator before running the smoke suite.</p>}
    <section className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Contracts" value={END_TO_END_PROBES.length} icon={ShieldCheck} /><Metric label="Passed" value={totals.passed} icon={CheckCircle2} tone="green" /><Metric label="Protected" value={totals.protected} icon={ShieldCheck} tone="blue" /><Metric label="Failed" value={totals.failed} icon={CircleAlert} tone="red" /></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800"><h3 className="font-bold">Test session</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><Info label="Signed-in role" value={user?.roles?.join(", ") || user?.account_type || "Unknown"} /><Info label="API target" value={API_BASE_URL} /><Info label="Safety" value="GET requests only" /></div></section>
    <section className="space-y-4">{roles.map((role) => <RoleGroup key={role} role={role} probes={END_TO_END_PROBES.filter((probe) => probe.role === role)} results={results} />)}</section>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><header className="border-b p-4 dark:border-slate-700"><div className="flex items-center gap-2"><MonitorSmartphone className="text-blue-600" size={19} /><h3 className="font-bold">Responsive acceptance matrix</h3></div><p className="mt-1 text-xs text-slate-500">Open each role workspace at the listed viewport and confirm no horizontal page overflow, clipped actions or unusable dialogs.</p><p className="mt-2 text-xs font-bold text-blue-600">{manualDone} / {manualTotal} checks confirmed in this session</p></header><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-700"><tr><th className="px-4 py-3">Viewport</th>{roles.map((role) => <th key={role} className="px-4 py-3">{pretty(role)}</th>)}</tr></thead><tbody className="divide-y dark:divide-slate-700">{RESPONSIVE_VIEWPORTS.map((viewport) => <tr key={viewport.width}><td className="px-4 py-3 font-bold">{viewport.label}<p className="text-xs font-normal text-slate-500">{viewport.width}px</p></td>{roles.map((role) => { const key = `${viewport.width}-${role}`; return <td key={role} className="px-4 py-3"><label className="inline-flex min-h-11 cursor-pointer items-center gap-2"><input type="checkbox" checked={Boolean(checked[key])} onChange={(e) => setChecked((current) => ({ ...current, [key]: e.target.checked }))} className="h-5 w-5 accent-blue" />Verified</label></td>; })}</tr>)}</tbody></table></div></section>
  </div>;
}
function RoleGroup({ role, probes, results }: { role: QaRole; probes: QaProbe[]; results: Record<string, ProbeResult> }) { return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800"><h3 className="font-bold capitalize">{role} workflow</h3><div className="mt-3 grid gap-3 lg:grid-cols-3">{probes.map((probe) => { const result = results[probe.id]; return <article key={probe.id} className="rounded-xl border p-4 dark:border-slate-700"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-bold">{probe.label}</p><p className="mt-1 break-all font-mono text-[10px] text-slate-400">{probe.endpoint}</p></div>{result && <Status result={result} />}</div><p className="mt-3 text-xs text-slate-500">{result?.detail || probe.expected}</p><div className="mt-3 flex items-center justify-between gap-2"><Link href={probe.frontendRoute} className="inline-flex min-h-10 items-center gap-1 text-xs font-bold text-blue-600">Open page <ExternalLink size={13} /></Link>{result && <span className="text-[10px] text-slate-400">{result.duration}ms · HTTP {result.status || "network"}</span>}</div></article>; })}</div></section>; }
function Status({ result }: { result: ProbeResult }) { const style = result.outcome === "passed" ? "bg-emerald-100 text-emerald-700" : result.outcome === "protected" ? "bg-blue-100 text-blue-700" : "bg-red-100 text-red-700"; return <span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${style}`}>{result.outcome}</span>; }
function Metric({ label, value, icon: Icon, tone = "slate" }: { label: string; value: number; icon: typeof ShieldCheck; tone?: string }) { const color = tone === "green" ? "text-emerald-600" : tone === "blue" ? "text-blue-600" : tone === "red" ? "text-red-600" : "text-slate-600"; return <article className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><Icon size={18} className={color} /><p className="mt-3 text-2xl font-bold">{value}</p><p className="text-xs text-slate-500">{label}</p></article>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-slate-100 p-3 dark:bg-slate-700"><p className="break-all text-xs font-bold">{value}</p><p className="mt-1 text-[10px] text-slate-500 dark:text-slate-300">{label}</p></div>; }
