"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Coupon, DiscountRule, PromotionCampaign, createCoupon, createDiscount, createPromotionCampaign, listCoupons, listDiscounts, listPromotionCampaigns, updateCoupon, updateDiscount, updatePromotionCampaign } from "@/lib/api/endpoints/admin";

export type PromotionView = "coupons" | "discounts" | "campaigns";
type Row = Coupon | DiscountRule | PromotionCampaign;
const pretty = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (l) => l.toUpperCase());
const money = (value: number, currency = "TZS") => new Intl.NumberFormat("en-TZ", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);

export default function AdminPromotions({ view }: { view: PromotionView }) {
  const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState<string | null>(null);
  const title = view === "coupons" ? "Coupons" : view === "discounts" ? "Discount Rules" : "Campaigns";
  const load = async () => { setLoading(true); setError(""); try { setRows(await (view === "coupons" ? listCoupons() : view === "discounts" ? listDiscounts() : listPromotionCampaigns())); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load promotions"); } finally { setLoading(false); } };
  useEffect(() => { setShowForm(false); void load(); }, [view]);
  const filtered = useMemo(() => rows.filter((row) => ("code" in row ? `${row.code} ${row.description ?? ""}` : `${row.name} ${row.description ?? ""}`).toLowerCase().includes(query.toLowerCase())), [rows, query]);
  const active = rows.filter((row) => "is_active" in row ? row.is_active : row.status === "active").length;
  const scheduled = rows.filter((row) => "status" in row && row.status === "scheduled").length;
  const usage = rows.reduce((sum, row) => sum + ("usage_count" in row ? row.usage_count : "conversions" in row ? row.conversions : 0), 0);

  const toggle = async (row: Row) => { setBusy(row.id); setError(""); try { if ("code" in row) await updateCoupon(row.id, { is_active: !row.is_active }); else if ("applies_to" in row) await updateDiscount(row.id, { is_active: !row.is_active }); else await updatePromotionCampaign(row.id, { status: row.status === "active" ? "paused" : "active" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Action failed"); } finally { setBusy(null); } };

  return <div className="space-y-5">
    <section className="rounded-3xl bg-gradient-to-br from-[#111827] via-[#263244] to-[#f47524] p-6 text-white shadow-lg sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/60">Growth operations</p><div className="mt-2 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-3xl font-semibold">{title}</h2><p className="mt-2 max-w-2xl text-sm text-white/75">Configure eligibility, offer value and activation dates, then monitor usage from the same workspace.</p></div><button onClick={() => setShowForm(true)} className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-gray-900">+ Create {view === "campaigns" ? "campaign" : view === "discounts" ? "discount" : "coupon"}</button></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total", rows.length],["Active", active],["Scheduled", scheduled],[view === "campaigns" ? "Conversions" : "Redemptions", usage]].map(([label,value]) => <article key={label} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold text-gray-900">{value}</p></article>)}</section>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="flex gap-3 border-b p-5"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}`} className="min-w-0 flex-1 rounded-xl border border-gray-200 px-4 py-2.5 text-sm focus:border-orange-400 focus:outline-none"/><button onClick={() => void load()} className="rounded-xl border px-4 text-sm font-semibold">Refresh</button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{[view === "coupons" ? "Coupon" : view === "discounts" ? "Rule" : "Campaign", "Offer / objective", "Eligibility / audience", "Validity", "Performance", "Status", ""].map((h) => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{filtered.map((row) => <PromotionRow key={row.id} row={row} onToggle={() => void toggle(row)} busy={busy === row.id}/>)}</tbody></table></div>
      {loading ? <p className="p-10 text-center text-gray-500">Loading {title.toLowerCase()}...</p> : filtered.length === 0 ? <div className="p-10 text-center"><p className="text-3xl">🏷️</p><p className="mt-2 font-medium">No {title.toLowerCase()} found</p><p className="mt-1 text-sm text-gray-500">Create the first one to begin this promotion flow.</p></div> : null}
    </section>
    {showForm && <PromotionForm view={view} onClose={() => setShowForm(false)} onSaved={async () => { setShowForm(false); await load(); }} onError={setError}/>}
  </div>;
}

function PromotionRow({ row, onToggle, busy }: { row: Row; onToggle: () => void; busy: boolean }) {
  const coupon = "code" in row; const discount = "applies_to" in row; const campaign = "objective" in row;
  const name = coupon ? row.code : row.name; const active = coupon || discount ? row.is_active : row.status === "active";
  const start = coupon ? row.valid_from : discount ? row.valid_from : row.starts_at; const end = coupon ? row.valid_until : discount ? row.valid_until : row.ends_at;
  const offer = campaign ? pretty(row.objective) : `${row.discount_type === "percentage" ? `${row.discount_value}%` : money(row.discount_value)} off`;
  const audience = coupon ? (row.minimum_order_amount ? `Orders above ${money(row.minimum_order_amount)}` : "All eligible carts") : discount ? pretty(row.applies_to) : pretty(row.audience);
  const performance = coupon ? `${row.usage_count}${row.usage_limit ? ` / ${row.usage_limit}` : ""} uses` : discount ? `Priority ${row.priority}` : `${row.conversions} conversions`;
  const status = coupon || discount ? (row.is_active ? "active" : "inactive") : row.status;
  return <tr className="hover:bg-gray-50"><td className="px-5 py-4"><p className="font-semibold text-gray-900">{name}</p><p className="max-w-[210px] truncate text-xs text-gray-500">{row.description || "No description"}</p></td><td className="px-5 py-4 font-medium">{offer}</td><td className="px-5 py-4">{audience}</td><td className="px-5 py-4 text-xs text-gray-500">{start ? new Date(start).toLocaleDateString() : "Now"} → {end ? new Date(end).toLocaleDateString() : "No end"}</td><td className="px-5 py-4">{performance}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${active ? "bg-green-50 text-green-700" : status === "scheduled" ? "bg-blue-50 text-blue-700" : "bg-gray-100 text-gray-600"}`}>{pretty(status)}</span></td><td className="px-5 py-4"><button disabled={busy} onClick={onToggle} className="font-semibold text-orange-600 disabled:opacity-40">{busy ? "Saving..." : active ? "Pause" : "Activate"}</button></td></tr>;
}

function PromotionForm({ view, onClose, onSaved, onError }: { view: PromotionView; onClose: () => void; onSaved: () => void; onError: (value: string) => void }) {
  const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const data = Object.fromEntries(new FormData(event.currentTarget)); try { if (view === "coupons") await createCoupon({ code: String(data.code).trim().toUpperCase(), description: String(data.description), discount_type: String(data.discount_type), discount_value: Number(data.discount_value), minimum_order_amount: data.minimum_order_amount ? Number(data.minimum_order_amount) : null, usage_limit: data.usage_limit ? Number(data.usage_limit) : null, valid_from: data.valid_from ? new Date(String(data.valid_from)).toISOString() : null, valid_until: data.valid_until ? new Date(String(data.valid_until)).toISOString() : null, is_active: true }); else if (view === "discounts") await createDiscount({ name: String(data.name), description: String(data.description), discount_type: String(data.discount_type), discount_value: Number(data.discount_value), applies_to: String(data.applies_to), minimum_order_amount: data.minimum_order_amount ? Number(data.minimum_order_amount) : null, priority: Number(data.priority), valid_from: data.valid_from ? new Date(String(data.valid_from)).toISOString() : null, valid_until: data.valid_until ? new Date(String(data.valid_until)).toISOString() : null, is_active: true }); else await createPromotionCampaign({ name: String(data.name), description: String(data.description), objective: String(data.objective), audience: String(data.audience), channel: String(data.channel), budget: data.budget ? Number(data.budget) : null, currency: "TZS", starts_at: data.starts_at ? new Date(String(data.starts_at)).toISOString() : null, ends_at: data.ends_at ? new Date(String(data.ends_at)).toISOString() : null, status: "draft" }); await onSaved(); } catch (e) { onError(e instanceof Error ? e.message : "Could not save promotion"); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-[80] flex items-end justify-end bg-black/40" onClick={onClose}><aside onClick={(e) => e.stopPropagation()} className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-orange-600">New promotion</p><h3 className="mt-1 text-2xl font-semibold">Create {view.slice(0,-1)}</h3></div><button onClick={onClose} className="text-2xl text-gray-400">×</button></div><form onSubmit={submit} className="mt-6 space-y-4">{view === "coupons" ? <CouponFields/> : view === "discounts" ? <DiscountFields/> : <CampaignFields/>}<button disabled={saving} className="w-full rounded-xl bg-[#111827] px-4 py-3 font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save as configured"}</button></form></aside></div>;
}
const Input = ({ label, name, type = "text", required = false }: { label: string; name: string; type?: string; required?: boolean }) => <label className="block text-sm font-medium text-gray-700">{label}<input name={name} type={type} required={required} min={type === "number" ? 0 : undefined} className="mt-1.5 w-full rounded-xl border border-gray-200 px-3 py-2.5 outline-none focus:border-orange-400"/></label>;
const Select = ({ label, name, options }: { label: string; name: string; options: string[] }) => <label className="block text-sm font-medium text-gray-700">{label}<select name={name} className="mt-1.5 w-full rounded-xl border border-gray-200 px-3 py-2.5">{options.map((o) => <option key={o} value={o}>{pretty(o)}</option>)}</select></label>;
const Dates = ({ start = "valid_from", end = "valid_until" }: { start?: string; end?: string }) => <div className="grid grid-cols-2 gap-3"><Input label="Starts" name={start} type="datetime-local"/><Input label="Ends" name={end} type="datetime-local"/></div>;
function CouponFields(){return <><Input label="Coupon code" name="code" required/><Input label="Description" name="description"/><div className="grid grid-cols-2 gap-3"><Select label="Discount type" name="discount_type" options={["percentage","fixed_amount"]}/><Input label="Value" name="discount_value" type="number" required/></div><div className="grid grid-cols-2 gap-3"><Input label="Minimum order" name="minimum_order_amount" type="number"/><Input label="Usage limit" name="usage_limit" type="number"/></div><Dates/></>}
function DiscountFields(){return <><Input label="Rule name" name="name" required/><Input label="Description" name="description"/><div className="grid grid-cols-2 gap-3"><Select label="Discount type" name="discount_type" options={["percentage","fixed_amount"]}/><Input label="Value" name="discount_value" type="number" required/></div><Select label="Applies to" name="applies_to" options={["all_products","selected_products","selected_categories","shipping"]}/><div className="grid grid-cols-2 gap-3"><Input label="Minimum order" name="minimum_order_amount" type="number"/><Input label="Priority" name="priority" type="number"/></div><Dates/></>}
function CampaignFields(){return <><Input label="Campaign name" name="name" required/><Input label="Description" name="description"/><Select label="Objective" name="objective" options={["sales","customer_acquisition","retention","awareness"]}/><div className="grid grid-cols-2 gap-3"><Select label="Audience" name="audience" options={["all_customers","new_customers","returning_customers","sellers"]}/><Select label="Channel" name="channel" options={["marketplace","email","sms","multi_channel"]}/></div><Input label="Budget (TZS)" name="budget" type="number"/><Dates start="starts_at" end="ends_at"/></>}
