"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ClipboardList,Search,ChevronLeft,ChevronRight,Eye,RefreshCw,PackageCheck,Truck,Clock3} from "lucide-react";
import toast from "react-hot-toast";
import {sellerOrdersApi} from "@/lib/api/endpoints/seller-orders";
import type {SellerOrder,SellerOrderStatus,SellerOrderSummary} from "@/types/api/seller-order";
const statuses=["","new","accepted","processing","ready_to_ship","shipped","delivered","cancellation_requested","cancelled"] as const;
const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const money=(v:number|string,c="TZS")=>new Intl.NumberFormat("en-TZ",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(v||0));
export default function SellerOrders(){
 const [rows,setRows]=useState<SellerOrder[]>([]),[summary,setSummary]=useState<SellerOrderSummary|null>(null),[loading,setLoading]=useState(true);
 const [search,setSearch]=useState(""),[status,setStatus]=useState(""),[page,setPage]=useState(1),[size,setSize]=useState(20),[total,setTotal]=useState(0);
 const load=async()=>{setLoading(true);try{const [a,b]=await Promise.all([sellerOrdersApi.list({page,page_size:size,search:search.trim()||undefined,status:(status||undefined) as SellerOrderStatus|undefined}),sellerOrdersApi.summary()]);setRows(a.results);setTotal(a.total);setSummary(b)}catch(e:any){toast.error(e?.response?.data?.detail||"Unable to load seller orders") }finally{setLoading(false)}};
 useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>clearTimeout(t)},[page,size,search,status]);
 const pages=Math.max(1,Math.ceil(total/size));
 return <div className="space-y-5">
  <section className="rounded-2xl border border-[#e7ebf0] bg-white p-6 shadow-sm dark:border-white/10 dark:bg-[#1f2937]">
   <div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-[#f7941d]"><ClipboardList size={21}/></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#f7941d]">Seller Phase 4</p><h1 className="text-2xl font-bold dark:text-white">Orders & Fulfilment</h1></div></div>
   <p className="mt-3 text-sm text-slate-500">Accept customer orders, process and prepare packages, then dispatch them with tracking. Every order shown here is seller-scoped by the backend.</p>
   <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card icon={ClipboardList} label="Total orders" value={summary?.total_orders||0}/><Card icon={Clock3} label="New orders" value={summary?.new_orders||0}/><Card icon={PackageCheck} label="Ready to ship" value={summary?.ready_to_ship_orders||0}/><Card icon={Truck} label="Gross sales" value={money(summary?.gross_sales||0)}/></div>
  </section>
  <section className="overflow-hidden rounded-2xl border border-[#e7ebf0] bg-white shadow-sm dark:border-white/10 dark:bg-[#1f2937]">
   <div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:justify-between dark:border-white/10"><div><h2 className="font-bold dark:text-white">My Orders</h2><p className="text-xs text-slate-400">Backend search, status filter and pagination</p></div><div className="flex gap-2"><label className="relative"><Search size={15} className="absolute left-3 top-3.5 text-slate-400"/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search order..." className="h-11 rounded-xl border pl-9 pr-3 text-sm dark:border-white/10 dark:bg-white/5"/></label><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="h-11 rounded-xl border px-3 text-sm dark:border-white/10 dark:bg-white/5">{statuses.map(x=><option key={x} value={x}>{x?pretty(x):"All statuses"}</option>)}</select></div></div>
   {loading?<div className="p-14 text-center text-slate-500"><RefreshCw className="mx-auto animate-spin"/><p className="mt-2">Loading orders...</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-50 text-left text-[10px] uppercase tracking-wider text-slate-400 dark:bg-white/5"><tr>{["Order","Customer","Items","Seller total","Delivery","Status","Created","Action"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y dark:divide-white/10">{rows.map(o=><tr key={o.id}><td className="px-5 py-4"><b className="dark:text-white">#{o.order_id.slice(0,8)}</b><p className="text-xs text-slate-400">Seller order {o.id.slice(0,8)}</p></td><td className="px-5 py-4"><b className="dark:text-white">{o.customer_name}</b><p className="text-xs text-slate-400">{o.customer_phone||"—"}</p></td><td className="px-5 py-4">{o.item_count}</td><td className="px-5 py-4 font-semibold">{money(o.seller_subtotal,o.currency)}</td><td className="px-5 py-4"><p>{o.shipping_method_name||"—"}</p><p className="text-xs text-slate-400">{o.shipping_carrier||"Carrier pending"}</p></td><td className="px-5 py-4"><Badge status={o.seller_status}/></td><td className="px-5 py-4 text-xs text-slate-500">{new Date(o.created_at).toLocaleString()}</td><td className="px-5 py-4"><Link href={`/seller/orders/${o.id}`} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold hover:bg-slate-50 dark:border-white/10"><Eye size={14}/>Review</Link></td></tr>)}{!rows.length&&<tr><td colSpan={8} className="p-14 text-center text-slate-400">No seller orders found.</td></tr>}</tbody></table></div>}
   <div className="flex flex-col gap-3 border-t p-4 sm:flex-row sm:items-center sm:justify-between dark:border-white/10"><span className="text-sm text-slate-500">{total} orders · Page {page} of {pages}</span><div className="flex gap-2"><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}} className="rounded-xl border px-3 text-sm dark:border-white/10 dark:bg-white/5">{[10,20,50,100].map(n=><option key={n}>{n}</option>)}</select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-xl border p-2 disabled:opacity-40 dark:border-white/10"><ChevronLeft/></button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)} className="rounded-xl border p-2 disabled:opacity-40 dark:border-white/10"><ChevronRight/></button></div></div>
  </section>
 </div>
}
function Card({icon:Icon,label,value}:{icon:any;label:string;value:string|number}){return <div className="rounded-xl border bg-slate-50 p-4 dark:border-white/10 dark:bg-white/[.03]"><div className="flex justify-between"><div><p className="text-xl font-bold dark:text-white">{value}</p><p className="text-xs text-slate-500">{label}</p></div><Icon className="text-[#f7941d]" size={19}/></div></div>}
export function Badge({status}:{status:string}){return <span className="inline-flex rounded-full border border-orange-200 bg-orange-50 px-2.5 py-1 text-[10px] font-bold uppercase text-orange-700">{pretty(status)}</span>}
