"use client";

import { deliveryVerificationApi } from "@/lib/api/endpoints/delivery-verification";
import { resolveBackendDocumentUrl } from "@/lib/documents/backend-document";
import type { DeliveryDisputeReason, DeliveryProof } from "@/types/api/delivery-verification";
import { AlertTriangle, CheckCircle2, Clock3, Eye, MapPin, RefreshCw, ShieldCheck, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { createPortal } from "react-dom";

const reasons: Array<{ value: DeliveryDisputeReason; label: string }> = [
  { value: "not_received", label: "Delivery not received" }, { value: "wrong_recipient", label: "Delivered to the wrong recipient" },
  { value: "damaged", label: "Package arrived damaged" }, { value: "wrong_location", label: "Evidence is from the wrong location" },
  { value: "other", label: "Another delivery problem" },
];
const pretty = (value: string) => value.replaceAll("_", " ");
const date = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const message = (error: unknown) => error instanceof Error ? error.message : "The request could not be completed.";

export default function CustomerDeliveryVerification() {
  const [proofs, setProofs] = useState<DeliveryProof[]>([]); const [filter, setFilter] = useState(""); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(""); const [selected, setSelected] = useState<DeliveryProof | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setProofs(await deliveryVerificationApi.mine()); } catch (err) { setError(message(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = filter ? proofs.filter((proof) => proof.status === filter) : proofs;

  return <div className="space-y-5"><header className="flex flex-col gap-3 rounded-2xl border border-[#e2e8f0] bg-white p-4 shadow-sm sm:flex-row sm:items-end sm:justify-between sm:p-6 dark:border-white/10 dark:bg-darkTheme-card"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#f7941d]">Proof of delivery</p><h1 className="mt-1 text-xl font-bold text-[#0f172a] sm:text-2xl dark:text-white">Delivery verification</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#64748b]">View delivery evidence, recipient OTP results, location checks, and settlement status for every shipment.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#e2e8f0] px-4 text-sm font-semibold text-[#475569] disabled:opacity-50 dark:border-white/10 dark:text-white"><RefreshCw size={16} className={loading ? "animate-spin" : ""} />Refresh</button></header>
    <section className="flex flex-col gap-3 rounded-2xl border border-[#e2e8f0] bg-white p-3 sm:flex-row sm:items-center sm:justify-between dark:border-white/10 dark:bg-darkTheme-card"><p className="flex items-center gap-2 text-sm text-[#64748b]"><ShieldCheck size={17} />OTP and GPS verification protect your delivery.</p><select value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter delivery proofs" className="min-h-11 rounded-xl border border-[#e2e8f0] bg-white px-3 text-sm capitalize dark:border-white/10 dark:bg-darkTheme-bg"><option value="">All delivery states</option>{["pending_otp", "verified", "disputed", "expired"].map((status) => <option key={status} value={status}>{pretty(status)}</option>)}</select></section>
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {loading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-72 animate-pulse rounded-2xl bg-[#e2e8f0] dark:bg-white/5" />)}</div> : visible.length ? <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map((proof) => <ProofCard key={proof.id} proof={proof} open={() => setSelected(proof)} />)}</section> : !error && <div className="rounded-2xl border border-dashed border-[#cbd5e1] bg-white p-9 text-center dark:border-white/10 dark:bg-darkTheme-card"><ShieldCheck className="mx-auto text-[#94a3b8]" size={31} /><h2 className="mt-3 font-bold dark:text-white">No delivery proofs found</h2><p className="mt-1 text-sm text-[#64748b]">Delivery evidence appears here when a courier reaches your destination.</p></div>}
    {selected && <ProofPanel proof={selected} close={() => setSelected(null)} changed={() => { setSelected(null); void load(); }} />}
  </div>;
}

function ProofCard({ proof, open }: { proof: DeliveryProof; open: () => void }) {
  const statusStyle = proof.status === "verified" ? "bg-emerald-100 text-emerald-800" : proof.status === "disputed" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-800";
  return <article className="overflow-hidden rounded-2xl border border-[#e2e8f0] bg-white shadow-sm dark:border-white/10 dark:bg-darkTheme-card"><div className="relative aspect-[16/10] bg-[#f1f5f9]"><img src={resolveBackendDocumentUrl(proof.photo_url)} alt="Delivery evidence" className="h-full w-full object-cover" /><span className={`absolute left-3 top-3 rounded-full px-2.5 py-1 text-xs font-bold capitalize ${statusStyle}`}>{pretty(proof.status)}</span></div><div className="p-4"><p className="break-all font-bold text-[#0f172a] dark:text-white">Order {proof.order_id.slice(0, 8)}</p><p className="mt-1 text-sm text-[#64748b]">Recipient: {proof.recipient_name}</p><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><span className="text-[#94a3b8]">GPS distance</span><p className="mt-1 font-semibold">{Number(proof.distance_from_destination_meters).toLocaleString()} m</p></div><div><span className="text-[#94a3b8]">Settlement</span><p className="mt-1 font-semibold capitalize">{pretty(proof.settlement_status)}</p></div></div><button onClick={open} className="mt-4 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#0f172a] text-sm font-semibold text-white"><Eye size={17} />View proof</button></div></article>;
}

function ProofPanel({ proof, close, changed }: { proof: DeliveryProof; close: () => void; changed: () => void }) {
  const [disputing, setDisputing] = useState(false); const [reason, setReason] = useState<DeliveryDisputeReason>("not_received"); const [notes, setNotes] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const dispute = async (event: FormEvent) => { event.preventDefault(); if (reason === "other" && !notes.trim()) { setError("Please describe the delivery problem."); return; } setBusy(true); setError(""); try { await deliveryVerificationApi.dispute(proof.id, { reason, notes: notes.trim() || undefined }); changed(); } catch (err) { setError(message(err)); } finally { setBusy(false); } };
  return createPortal(<div className="fixed inset-0 z-[1000] flex items-center justify-center overflow-hidden bg-black/60 p-2 sm:p-4" role="dialog" aria-modal="true" aria-label="Delivery proof"><div className="flex max-h-[calc(100dvh-1rem)] w-[min(96vw,48rem)] flex-col overflow-hidden rounded-2xl bg-white shadow-2xl sm:max-h-[calc(100dvh-2rem)] dark:bg-darkTheme-card"><header className="z-20 flex shrink-0 items-start justify-between border-b bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-darkTheme-card"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#f7941d]">Delivery evidence</p><h2 className="mt-1 text-lg font-bold dark:text-white">Order {proof.order_id.slice(0, 8)}</h2></div><button onClick={close} aria-label="Close" className="grid min-h-11 min-w-11 place-items-center rounded-xl bg-[#f1f5f9] dark:bg-white/5"><X size={19} /></button></header><div className="min-h-0 flex-1 space-y-5 overflow-y-auto p-4 pb-6 sm:p-6 sm:pb-8"><img src={resolveBackendDocumentUrl(proof.photo_url)} alt="Full delivery evidence" className="max-h-[55vh] w-full rounded-2xl bg-[#f1f5f9] object-contain" />{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<dl className="grid gap-3 rounded-2xl bg-[#f8fafc] p-4 text-sm sm:grid-cols-2 dark:bg-white/5"><Info label="Status" value={pretty(proof.status)} /><Info label="Recipient" value={proof.recipient_name} /><Info label="Recipient phone" value={proof.recipient_phone_last4 ? `Ending ${proof.recipient_phone_last4}` : "Not recorded"} /><Info label="OTP attempts" value={String(proof.otp_attempts)} /><Info label="Evidence captured" value={date(proof.created_at)} /><Info label="OTP expires" value={date(proof.otp_expires_at)} /><Info label="Distance from destination" value={`${Number(proof.distance_from_destination_meters).toLocaleString()} metres`} /><Info label="Settlement" value={pretty(proof.settlement_status)} /><div className="sm:col-span-2"><dt className="text-xs text-[#64748b]">Delivery coordinates</dt><dd className="mt-1 flex items-center gap-1 font-medium"><MapPin size={15} />{proof.delivery_latitude}, {proof.delivery_longitude}</dd></div>{proof.notes && <div className="sm:col-span-2"><dt className="text-xs text-[#64748b]">Courier note</dt><dd className="mt-1 whitespace-pre-wrap">{proof.notes}</dd></div>}</dl>
      <section><h3 className="font-bold dark:text-white">Verification timeline</h3><div className="mt-3 space-y-3">{proof.events.length ? [...proof.events].reverse().map((event) => <div key={event.id} className="border-l-2 border-[#f7941d] pl-3"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-semibold capitalize">{pretty(event.action)}</span><time className="text-xs text-[#64748b]">{date(event.created_at)}</time></div>{event.note && <p className="mt-1 text-sm text-[#64748b]">{event.note}</p>}</div>) : <p className="text-sm text-[#64748b]">No audit events recorded.</p>}</div></section>
      {proof.status === "pending_otp" && (disputing ? <form onSubmit={dispute} className="space-y-3 rounded-2xl border border-red-200 bg-red-50 p-4"><h3 className="flex items-center gap-2 font-bold text-red-800"><AlertTriangle size={18} />Dispute this delivery attempt</h3><select value={reason} onChange={(event) => setReason(event.target.value as DeliveryDisputeReason)} className="min-h-11 w-full rounded-xl border border-red-200 bg-white px-3 text-sm">{reasons.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><textarea maxLength={2000} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Explain what happened so support can investigate." className="min-h-28 w-full rounded-xl border border-red-200 bg-white p-3 text-sm" /><div className="grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => { setDisputing(false); setError(""); }} className="min-h-11 rounded-xl border border-red-300 font-semibold text-red-700">Go back</button><button disabled={busy} className="min-h-11 rounded-xl bg-red-700 font-semibold text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit dispute"}</button></div></form> : <button onClick={() => setDisputing(true)} className="min-h-12 w-full rounded-xl border border-red-300 px-4 text-sm font-bold text-red-700">I did not receive this delivery correctly</button>)}
      {proof.status === "verified" && <div className="flex items-start gap-3 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="shrink-0" /><div><p className="font-bold">Delivery verified</p><p className="mt-1">Recipient OTP and GPS evidence were accepted{proof.verified_at ? ` on ${date(proof.verified_at)}` : ""}.</p></div></div>}{proof.status === "disputed" && <div className="rounded-2xl bg-red-50 p-4 text-sm text-red-800"><p className="font-bold">Delivery disputed</p><p className="mt-1 capitalize">{pretty(proof.dispute_reason || "problem reported")}</p>{proof.dispute_notes && <p className="mt-1 whitespace-pre-wrap">{proof.dispute_notes}</p>}</div>}
    </div><footer className="z-20 shrink-0 border-t bg-white p-3 sm:p-4 dark:border-white/10 dark:bg-darkTheme-card"><button type="button" onClick={close} className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-4 text-sm font-bold text-slate-700 shadow-sm transition hover:bg-slate-50 dark:border-white/15 dark:bg-white/5 dark:text-white dark:hover:bg-white/10">Close delivery proof</button></footer></div></div>, document.body);
}

function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-[#64748b]">{label}</dt><dd className="mt-1 break-words font-medium capitalize text-[#0f172a] dark:text-white">{value}</dd></div>; }