"use client";

import { pickupVerificationApi } from "@/lib/api/endpoints/pickup-verification";
import { resolveBackendDocumentUrl } from "@/lib/documents/backend-document";
import type { CustomerPickupProof, PaginatedPickupProofs, PickupProofProblemReason, PickupProofStatus } from "@/types/api/pickup-verification";
import { AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Eye, MapPin, PackageCheck, RefreshCw, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

const statusOptions: Array<PickupProofStatus | ""> = ["", "pending", "approved", "disputed", "auto_approved"];
const problemOptions: Array<{ value: PickupProofProblemReason; label: string }> = [
  { value: "wrong_product", label: "Wrong product" }, { value: "wrong_variant", label: "Wrong variant" },
  { value: "wrong_quantity", label: "Wrong quantity" }, { value: "damaged", label: "Product is damaged" },
  { value: "photo_unclear", label: "Photo is unclear" }, { value: "other", label: "Another problem" },
];
const pretty = (value: string) => value.replaceAll("_", " ");
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const message = (error: unknown) => error instanceof Error ? error.message : "The request could not be completed.";

export default function PickupVerification() {
  const [data, setData] = useState<PaginatedPickupProofs | null>(null); const [page, setPage] = useState(1);
  const [status, setStatus] = useState<PickupProofStatus | "">(""); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(""); const [selected, setSelected] = useState<CustomerPickupProof | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await pickupVerificationApi.list({ page, page_size: 9, status: status || undefined })); } catch (err) { setError(message(err)); } finally { setLoading(false); } }, [page, status]);
  useEffect(() => { void load(); }, [load]);

  return <div className="space-y-5">
    <header className="flex flex-col gap-3 rounded-2xl border border-[#e2e8f0] bg-white p-4 shadow-sm sm:flex-row sm:items-end sm:justify-between sm:p-6 dark:border-white/10 dark:bg-darkTheme-card"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#f7941d]">Secure handover review</p><h1 className="mt-1 text-xl font-bold text-[#0f172a] sm:text-2xl dark:text-white">Pickup verification</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#64748b]">Review the courier’s pickup photo before your order leaves the seller. Approve when the package looks correct, or report a problem before the deadline.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#e2e8f0] px-4 text-sm font-semibold text-[#475569] disabled:opacity-50 dark:border-white/10 dark:text-white"><RefreshCw size={16} className={loading ? "animate-spin" : ""} />Refresh</button></header>
    <section className="flex flex-col gap-3 rounded-2xl border border-[#e2e8f0] bg-white p-3 sm:flex-row sm:items-center sm:justify-between dark:border-white/10 dark:bg-darkTheme-card"><div className="flex items-center gap-2 text-sm text-[#64748b]"><Clock3 size={17} /><span>Pending proofs need your attention before automatic approval.</span></div><select aria-label="Filter pickup proofs" value={status} onChange={(event) => { setStatus(event.target.value as PickupProofStatus | ""); setPage(1); }} className="min-h-11 rounded-xl border border-[#e2e8f0] bg-white px-3 text-sm capitalize outline-none focus:border-[#f7941d] dark:border-white/10 dark:bg-darkTheme-bg">{statusOptions.map((item) => <option key={item || "all"} value={item}>{item ? pretty(item) : "All verification states"}</option>)}</select></section>
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4"><p className="break-words text-sm text-red-700">{error}</p><button onClick={() => void load()} className="mt-3 min-h-11 rounded-xl bg-red-700 px-4 text-sm font-semibold text-white">Try again</button></div>}
    {loading && !data ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-72 animate-pulse rounded-2xl bg-[#e2e8f0] dark:bg-white/5" />)}</div> : data?.results.length ? <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.results.map((proof) => <ProofCard key={proof.id} proof={proof} open={() => setSelected(proof)} />)}</section> : !error && <div className="rounded-2xl border border-dashed border-[#cbd5e1] bg-white p-9 text-center dark:border-white/10 dark:bg-darkTheme-card"><PackageCheck className="mx-auto text-[#94a3b8]" size={30} /><h2 className="mt-3 font-bold text-[#0f172a] dark:text-white">No pickup proofs found</h2><p className="mt-1 text-sm text-[#64748b]">Proofs appear here after a courier collects a seller package.</p></div>}
    {data && data.total_pages > 1 && <nav className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#e2e8f0] bg-white p-3 text-sm dark:border-white/10 dark:bg-darkTheme-card"><span className="text-[#64748b]">{data.total} proof(s) · Page {page} of {data.total_pages}</span><div className="flex gap-2"><button aria-label="Previous page" disabled={page <= 1} onClick={() => setPage(page - 1)} className="grid min-h-11 min-w-11 place-items-center rounded-xl border disabled:opacity-40"><ChevronLeft /></button><button aria-label="Next page" disabled={page >= data.total_pages} onClick={() => setPage(page + 1)} className="grid min-h-11 min-w-11 place-items-center rounded-xl border disabled:opacity-40"><ChevronRight /></button></div></nav>}
    {selected && <ReviewPanel proof={selected} close={() => setSelected(null)} changed={() => { setSelected(null); void load(); }} />}
  </div>;
}

function ProofCard({ proof, open }: { proof: CustomerPickupProof; open: () => void }) {
  const pending = proof.status === "pending"; const deadlinePassed = new Date(proof.review_deadline).getTime() <= Date.now();
  return <article className="overflow-hidden rounded-2xl border border-[#e2e8f0] bg-white shadow-sm dark:border-white/10 dark:bg-darkTheme-card"><div className="relative aspect-[16/10] bg-[#f1f5f9]"><img src={resolveBackendDocumentUrl(proof.photo_url)} alt="Courier pickup evidence" className="h-full w-full object-cover" /><span className={`absolute left-3 top-3 rounded-full px-2.5 py-1 text-xs font-bold capitalize ${pending ? "bg-amber-100 text-amber-800" : proof.status === "disputed" ? "bg-red-100 text-red-700" : "bg-emerald-100 text-emerald-700"}`}>{pretty(proof.status)}</span></div><div className="p-4"><p className="break-all font-bold text-[#0f172a] dark:text-white">Order {proof.order_id.slice(0, 8)}</p><p className="mt-1 text-xs text-[#64748b]">Uploaded {formatDate(proof.created_at)}</p><div className="mt-3 flex items-start gap-2 rounded-xl bg-[#f8fafc] p-3 text-xs text-[#64748b] dark:bg-white/5"><Clock3 className="mt-0.5 shrink-0" size={15} /><span>{pending && !deadlinePassed ? `Review before ${formatDate(proof.review_deadline)}` : `Review deadline: ${formatDate(proof.review_deadline)}`}</span></div><button onClick={open} className="mt-4 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#0f172a] px-4 text-sm font-semibold text-white"><Eye size={17} />{pending ? "Review proof" : "View details"}</button></div></article>;
}

function ReviewPanel({ proof, close, changed }: { proof: CustomerPickupProof; close: () => void; changed: () => void }) {
  const [reporting, setReporting] = useState(false); const [reason, setReason] = useState<PickupProofProblemReason>("photo_unclear"); const [notes, setNotes] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const pending = proof.status === "pending";
  const approve = async () => { setBusy(true); setError(""); try { await pickupVerificationApi.approve(proof.id); changed(); } catch (err) { setError(message(err)); } finally { setBusy(false); } };
  const report = async (event: FormEvent) => { event.preventDefault(); if (reason === "other" && !notes.trim()) { setError("Please describe the pickup problem."); return; } setBusy(true); setError(""); try { await pickupVerificationApi.reportProblem(proof.id, { reason, notes: notes.trim() || undefined }); changed(); } catch (err) { setError(message(err)); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/60 sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-label="Review pickup proof"><div className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-t-2xl bg-white shadow-2xl sm:rounded-2xl dark:bg-darkTheme-card"><header className="sticky top-0 z-10 flex items-start justify-between gap-3 border-b bg-white p-4 sm:p-5 dark:border-white/10 dark:bg-darkTheme-card"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#f7941d]">Pickup evidence</p><h2 className="mt-1 text-lg font-bold dark:text-white">Order {proof.order_id.slice(0, 8)}</h2></div><button onClick={close} aria-label="Close review" className="grid min-h-11 min-w-11 place-items-center rounded-xl bg-[#f1f5f9] dark:bg-white/5"><X size={19} /></button></header><div className="space-y-5 p-4 sm:p-6"><img src={resolveBackendDocumentUrl(proof.photo_url)} alt="Full pickup evidence" className="max-h-[55vh] w-full rounded-2xl bg-[#f1f5f9] object-contain" />{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<dl className="grid gap-3 rounded-2xl bg-[#f8fafc] p-4 text-sm sm:grid-cols-2 dark:bg-white/5"><Info label="Status" value={pretty(proof.status)} /><Info label="Courier reference" value={proof.courier_reference || "Not provided"} /><Info label="Uploaded" value={formatDate(proof.created_at)} /><Info label="Review deadline" value={formatDate(proof.review_deadline)} /><div className="sm:col-span-2"><dt className="text-xs text-[#64748b]">Pickup coordinates</dt><dd className="mt-1 flex items-center gap-1 font-medium"><MapPin size={15} />{proof.pickup_latitude}, {proof.pickup_longitude}</dd></div>{proof.notes && <div className="sm:col-span-2"><dt className="text-xs text-[#64748b]">Courier note</dt><dd className="mt-1 whitespace-pre-wrap">{proof.notes}</dd></div>}</dl>
      {pending ? reporting ? <form onSubmit={report} className="space-y-3 rounded-2xl border border-red-200 bg-red-50 p-4"><h3 className="flex items-center gap-2 font-bold text-red-800"><AlertTriangle size={18} />Report a pickup problem</h3><select value={reason} onChange={(event) => setReason(event.target.value as PickupProofProblemReason)} className="min-h-11 w-full rounded-xl border border-red-200 bg-white px-3 text-sm">{problemOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={2000} placeholder="Explain what is wrong so our support team can investigate." className="min-h-28 w-full rounded-xl border border-red-200 bg-white p-3 text-sm" /><div className="grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => { setReporting(false); setError(""); }} className="min-h-11 rounded-xl border border-red-300 text-sm font-semibold text-red-700">Go back</button><button disabled={busy} className="min-h-11 rounded-xl bg-red-700 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit problem"}</button></div></form> : <div className="grid gap-3 sm:grid-cols-2"><button onClick={() => setReporting(true)} disabled={busy} className="min-h-12 rounded-xl border border-red-300 px-4 text-sm font-bold text-red-700 disabled:opacity-50">Report a problem</button><button onClick={() => void approve()} disabled={busy} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white disabled:opacity-50"><CheckCircle2 size={18} />{busy ? "Approving…" : "Approve pickup"}</button></div> : <div className={`rounded-2xl p-4 text-sm ${proof.status === "disputed" ? "bg-red-50 text-red-800" : "bg-emerald-50 text-emerald-800"}`}><p className="font-bold capitalize">Pickup {pretty(proof.status)}</p>{proof.problem_reason && <p className="mt-1">Reason: {pretty(proof.problem_reason)}</p>}{proof.problem_notes && <p className="mt-1 whitespace-pre-wrap">{proof.problem_notes}</p>}</div>}
    </div></div></div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-[#64748b]">{label}</dt><dd className="mt-1 break-words font-medium capitalize text-[#0f172a] dark:text-white">{value}</dd></div>; }
