"use client";

import { logisticsBusinessApi } from "@/lib/api/endpoints/logistics-business";
import type { LogisticsWallet, Payout, PayoutAccount, PayoutAccountCreate, WalletTransaction } from "@/types/api/logistics-business";
import { ArrowDownToLine, Building2, CircleDollarSign, CreditCard, Plus, RefreshCw, WalletCards, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

const msg = (error: unknown) => error instanceof Error ? error.message : "The request could not be completed.";
const money = (value: string | number, currency = "TZS") => new Intl.NumberFormat("en-TZ", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value));
const date = (value: string) => new Intl.DateTimeFormat("en-TZ", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const pretty = (value: string) => value.replaceAll("_", " ");

export default function LogisticsWalletPage() {
  const [wallet, setWallet] = useState<LogisticsWallet | null>(null); const [accounts, setAccounts] = useState<PayoutAccount[]>([]);
  const [transactions, setTransactions] = useState<WalletTransaction[]>([]); const [payouts, setPayouts] = useState<Payout[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [modal, setModal] = useState<"account" | "payout" | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [w, a, t, p] = await Promise.all([logisticsBusinessApi.wallet(), logisticsBusinessApi.accounts(), logisticsBusinessApi.transactions(), logisticsBusinessApi.payouts()]); setWallet(w); setAccounts(a); setTransactions(t.results); setPayouts(p.results); } catch (e) { setError(msg(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const cancel = async (id: string) => { if (!window.confirm("Cancel this payout request?")) return; try { await logisticsBusinessApi.cancelPayout(id); await load(); } catch (e) { setError(msg(e)); } };
  if (loading) return <div className="mx-auto grid max-w-7xl gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 8 }).map((_, i) => <div key={i} className="h-36 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800" />)}</div>;
  return <div className="mx-auto max-w-7xl space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue">Finance operations</p><h2 className="text-2xl font-bold">Wallet & payouts</h2><p className="mt-1 text-sm text-slate-500">Review earnings, payout destinations and withdrawal requests.</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><button onClick={() => void load()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border px-4 text-sm font-semibold"><RefreshCw size={17} />Refresh</button><button onClick={() => setModal("account")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue px-4 text-sm font-semibold text-white"><Plus size={17} />Account</button></div></header>
    {error && <p className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}{wallet?.is_frozen && <p className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">This wallet is frozen. New payout requests are unavailable until an administrator restores access.</p>}
    {wallet && <section className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Balance label="Available" value={wallet.available_balance} currency={wallet.currency} icon={CircleDollarSign} /><Balance label="Pending" value={wallet.pending_balance} currency={wallet.currency} icon={WalletCards} /><Balance label="Reserved" value={wallet.reserved_balance} currency={wallet.currency} icon={CreditCard} /><Balance label="Paid out" value={wallet.paid_out_balance} currency={wallet.currency} icon={ArrowDownToLine} /></section>}
    <section className="grid gap-5 xl:grid-cols-[1fr_1.35fr]"><Panel title="Payout accounts" action={<button disabled={!accounts.some((a) => a.is_active && a.verification_status === "verified") || wallet?.is_frozen} onClick={() => setModal("payout")} className="min-h-10 rounded-xl bg-blue px-3 text-xs font-bold text-white disabled:opacity-40">Request payout</button>}><div className="space-y-3">{accounts.map((a) => <article key={a.id} className="rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate font-bold">{a.provider}</p><p className="text-sm text-slate-500">{a.account_name} · {a.masked_account_number}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${a.verification_status === "verified" ? "bg-emerald-100 text-emerald-700" : a.verification_status === "rejected" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-800"}`}>{a.verification_status}</span></div><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500"><span className="capitalize">{pretty(a.account_type)}</span><span>{a.currency}</span>{a.is_default && <span className="font-bold text-blue">Default</span>}{!a.is_active && <span>Inactive</span>}</div></article>)}{!accounts.length && <Empty text="No payout account has been added." />}</div></Panel>
      <Panel title="Recent transactions"><div className="space-y-2">{transactions.map((t) => <article key={t.id} className="flex items-start justify-between gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="min-w-0"><p className="truncate text-sm font-bold capitalize">{pretty(t.transaction_type)}</p><p className="truncate text-xs text-slate-500">{t.description || t.reference}</p><p className="mt-1 text-[11px] text-slate-400">{date(t.created_at)}</p></div><p className="shrink-0 text-sm font-bold">{money(t.amount, t.currency)}</p></article>)}{!transactions.length && <Empty text="No wallet transactions yet." />}</div></Panel></section>
    <Panel title="Payout history"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{payouts.map((p) => <article key={p.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-center justify-between gap-2"><p className="text-lg font-bold">{money(p.amount, p.currency)}</p><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase dark:bg-slate-700">{p.status}</span></div><p className="mt-2 text-xs text-slate-500">Requested {date(p.requested_at)}</p>{p.company_note && <p className="mt-2 text-sm">{p.company_note}</p>}{p.status === "pending" && <button onClick={() => void cancel(p.id)} className="mt-3 min-h-10 w-full rounded-xl border border-red-200 text-xs font-bold text-red-700">Cancel request</button>}</article>)}{!payouts.length && <Empty text="No payout requests yet." />}</div></Panel>
    {modal === "account" && <AccountModal close={() => setModal(null)} saved={() => { setModal(null); void load(); }} />}{modal === "payout" && wallet && <PayoutModal accounts={accounts.filter((a) => a.is_active && a.verification_status === "verified")} currency={wallet.currency} available={wallet.available_balance} close={() => setModal(null)} saved={() => { setModal(null); void load(); }} />}
  </div>;
}

function Balance({ label, value, currency, icon: Icon }: { label: string; value: string; currency: string; icon: typeof WalletCards }) { return <article className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><Icon size={19} className="text-blue" /><p className="mt-3 break-words text-lg font-bold sm:text-xl">{money(value, currency)}</p><p className="text-xs text-slate-500">{label}</p></article>; }
function Panel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5 dark:border-slate-700 dark:bg-slate-800"><div className="mb-4 flex items-center justify-between gap-3"><h3 className="font-bold">{title}</h3>{action}</div>{children}</section>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed p-6 text-center text-sm text-slate-500">{text}</p>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/60 sm:items-center sm:p-4"><div className="max-h-[94vh] w-full max-w-lg overflow-y-auto rounded-t-2xl bg-white sm:rounded-2xl dark:bg-slate-900"><header className="sticky top-0 flex items-center justify-between border-b bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><h3 className="font-bold">{title}</h3><button onClick={close} className="grid min-h-11 min-w-11 place-items-center rounded-xl bg-slate-100 dark:bg-slate-800"><X /></button></header>{children}</div></div>; }
const input = "mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-transparent px-3 dark:border-slate-600";
function AccountModal({ close, saved }: { close: () => void; saved: () => void }) { const [f, setF] = useState<PayoutAccountCreate>({ account_type: "mobile_money", provider: "", account_name: "", account_number: "", currency: "TZS", is_default: false }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(""); try { await logisticsBusinessApi.createAccount(f); saved(); } catch (x) { setError(msg(x)); } finally { setBusy(false); } }; return <Modal title="Add payout account" close={close}><form onSubmit={submit} className="space-y-4 p-4 sm:p-6">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Account type<select className={input} value={f.account_type} onChange={(e) => setF({ ...f, account_type: e.target.value as PayoutAccountCreate["account_type"] })}><option value="mobile_money">Mobile money</option><option value="bank">Bank</option></select></label><label className="text-sm font-semibold">Provider<input required minLength={2} className={input} value={f.provider} onChange={(e) => setF({ ...f, provider: e.target.value })} /></label></div><label className="block text-sm font-semibold">Account name<input required minLength={2} className={input} value={f.account_name} onChange={(e) => setF({ ...f, account_name: e.target.value })} /></label><label className="block text-sm font-semibold">Account number<input required minLength={4} className={input} value={f.account_number} onChange={(e) => setF({ ...f, account_number: e.target.value })} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Currency<input required minLength={3} className={input} value={f.currency} onChange={(e) => setF({ ...f, currency: e.target.value.toUpperCase() })} /></label><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border px-3 text-sm font-semibold"><input type="checkbox" checked={f.is_default} onChange={(e) => setF({ ...f, is_default: e.target.checked })} />Make default</label></div><button disabled={busy} className="min-h-12 w-full rounded-xl bg-blue font-bold text-white disabled:opacity-50">{busy ? "Saving…" : "Add account"}</button></form></Modal>; }
function PayoutModal({ accounts, currency, available, close, saved }: { accounts: PayoutAccount[]; currency: string; available: string; close: () => void; saved: () => void }) { const [account, setAccount] = useState(accounts.find((a) => a.is_default)?.id || accounts[0]?.id || ""); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(""); try { await logisticsBusinessApi.requestPayout({ payout_account_id: account, amount: Number(amount), note: note || undefined }); saved(); } catch (x) { setError(msg(x)); } finally { setBusy(false); } }; return <Modal title="Request payout" close={close}><form onSubmit={submit} className="space-y-4 p-4 sm:p-6"><p className="rounded-xl bg-slate-100 p-3 text-sm dark:bg-slate-800">Available: <strong>{money(available, currency)}</strong></p>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="block text-sm font-semibold">Destination<select required className={input} value={account} onChange={(e) => setAccount(e.target.value)}>{accounts.map((a) => <option key={a.id} value={a.id}>{a.provider} · {a.masked_account_number}</option>)}</select></label><label className="block text-sm font-semibold">Amount ({currency})<input required type="number" min="0.01" step="0.01" max={available} className={input} value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label className="block text-sm font-semibold">Note<textarea maxLength={1000} className={`${input} min-h-24 py-3`} value={note} onChange={(e) => setNote(e.target.value)} /></label><button disabled={busy || !account} className="min-h-12 w-full rounded-xl bg-blue font-bold text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit payout request"}</button></form></Modal>; }
