"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CommunicationMessage, cancelCommunicationMessage, createCommunicationMessage, listCommunicationMessages, sendCommunicationMessage } from "@/lib/api/endpoints/admin";

export type CommunicationView = "notification" | "email" | "sms";
const config = { notification: { title: "Notifications", icon: "🔔", recipient: "Audience or user ID" }, email: { title: "Email Messages", icon: "✉️", recipient: "Recipient email" }, sms: { title: "SMS Messages", icon: "💬", recipient: "Recipient phone number" } };
const pretty = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (l) => l.toUpperCase());

export default function AdminCommunications({ view }: { view: CommunicationView }) {
  const [rows, setRows] = useState<CommunicationMessage[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [compose, setCompose] = useState(false); const [busy, setBusy] = useState<string | null>(null); const [selected, setSelected] = useState<CommunicationMessage | null>(null);
  const load = async () => { setLoading(true); setError(""); try { setRows(await listCommunicationMessages(view)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load messages"); } finally { setLoading(false); } };
  useEffect(() => { setCompose(false); setSelected(null); void load(); }, [view]);
  const filtered = useMemo(() => rows.filter((row) => `${row.title ?? ""} ${row.body} ${row.recipient ?? ""}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  const stats = { sent: rows.filter((r) => ["sent","delivered"].includes(r.status)).length, queued: rows.filter((r) => ["draft","scheduled","sending"].includes(r.status)).length, failed: rows.filter((r) => r.status === "failed").length, delivered: rows.filter((r) => r.status === "delivered").length };
  const action = async (row: CommunicationMessage, kind: "send" | "cancel") => { setBusy(row.id); setError(""); try { await (kind === "send" ? sendCommunicationMessage(row.id) : cancelCommunicationMessage(row.id)); setSelected(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Message action failed"); } finally { setBusy(null); } };
  return <div className="space-y-5">
    <section className="rounded-3xl bg-gradient-to-br from-[#111827] via-[#263244] to-[#f47524] p-6 text-white shadow-lg sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/60">Customer engagement</p><div className="mt-2 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-3xl font-semibold">{config[view].title}</h2><p className="mt-2 max-w-2xl text-sm text-white/75">Compose, schedule, dispatch and investigate delivery failures with a permanent message audit trail.</p></div><button onClick={() => setCompose(true)} className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-gray-900">+ Compose {view}</button></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Sent",stats.sent],["Delivered",stats.delivered],["Draft / queued",stats.queued],["Failed",stats.failed]].map(([label,value]) => <article key={label} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></article>)}</section>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="flex gap-3 border-b p-5"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search title, message or recipient" className="min-w-0 flex-1 rounded-xl border border-gray-200 px-4 py-2.5 text-sm focus:border-orange-400 focus:outline-none"/><button onClick={() => void load()} className="rounded-xl border px-4 text-sm font-semibold">Refresh</button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{["Message","Recipient / audience","Created","Schedule","Status",""].map((h) => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{filtered.map((row) => <tr key={row.id} className="hover:bg-gray-50"><td className="px-5 py-4"><p className="font-semibold">{row.title || `${pretty(view)} message`}</p><p className="max-w-[320px] truncate text-xs text-gray-500">{row.body}</p></td><td className="px-5 py-4"><p>{row.recipient || pretty(row.audience)}</p><p className="text-xs text-gray-500">{pretty(row.audience)}</p></td><td className="px-5 py-4 text-gray-500">{new Date(row.created_at).toLocaleString()}</td><td className="px-5 py-4 text-gray-500">{row.scheduled_at ? new Date(row.scheduled_at).toLocaleString() : "Manual send"}</td><td className="px-5 py-4"><Status value={row.status}/></td><td className="px-5 py-4"><button onClick={() => setSelected(row)} className="font-semibold text-orange-600">Review</button></td></tr>)}</tbody></table></div>{loading ? <p className="p-10 text-center text-gray-500">Loading messages...</p> : filtered.length === 0 ? <div className="p-10 text-center"><p className="text-3xl">{config[view].icon}</p><p className="mt-2 font-medium">No {config[view].title.toLowerCase()} yet</p><p className="mt-1 text-sm text-gray-500">Compose the first message to start the delivery flow.</p></div> : null}</section>
    {compose && <Composer view={view} onClose={() => setCompose(false)} onSaved={async () => { setCompose(false); await load(); }} onError={setError}/>}
    {selected && <div className="fixed inset-0 z-[80] flex items-end justify-end bg-black/40" onClick={() => setSelected(null)}><aside onClick={(e) => e.stopPropagation()} className="h-full w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase text-orange-600">Delivery record</p><h3 className="mt-1 text-xl font-semibold">{selected.title || "Untitled message"}</h3></div><button onClick={() => setSelected(null)} className="text-2xl text-gray-400">×</button></div><div className="mt-5 rounded-xl bg-gray-50 p-4 text-sm leading-6 whitespace-pre-wrap">{selected.body}</div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm">{[["Channel",pretty(selected.channel)],["Recipient",selected.recipient || pretty(selected.audience)],["Status",pretty(selected.status)],["Sent",selected.sent_at ? new Date(selected.sent_at).toLocaleString() : "Not sent"]].map(([k,v]) => <div key={k} className="rounded-xl border p-3"><dt className="text-gray-500">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>)}</dl>{selected.failure_reason && <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><p className="font-semibold">Delivery failure</p><p className="mt-1">{selected.failure_reason}</p></div>}<div className="mt-6 flex gap-3">{["draft","scheduled","failed"].includes(selected.status) && <button disabled={busy === selected.id} onClick={() => void action(selected,"send")} className="flex-1 rounded-xl bg-[#111827] px-4 py-3 font-semibold text-white disabled:opacity-50">{busy ? "Processing..." : selected.status === "failed" ? "Retry delivery" : "Send now"}</button>}{["draft","scheduled","failed"].includes(selected.status) && <button disabled={busy === selected.id} onClick={() => void action(selected,"cancel")} className="rounded-xl border border-red-200 px-4 py-3 font-semibold text-red-600">Cancel</button>}</div></aside></div>}
  </div>;
}

function Composer({ view, onClose, onSaved, onError }: { view: CommunicationView; onClose: () => void; onSaved: () => void; onError: (v: string) => void }) { const [saving,setSaving] = useState(false); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setSaving(true); const data = Object.fromEntries(new FormData(e.currentTarget)); try { await createCommunicationMessage({ channel:view, title:String(data.title || ""), body:String(data.body), audience:String(data.audience), recipient:String(data.recipient || "") || null, scheduled_at:data.scheduled_at ? new Date(String(data.scheduled_at)).toISOString() : null }); await onSaved(); } catch (err) { onError(err instanceof Error ? err.message : "Could not save message"); } finally { setSaving(false); } }; return <div className="fixed inset-0 z-[80] flex items-end justify-end bg-black/40" onClick={onClose}><aside onClick={(e) => e.stopPropagation()} className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase text-orange-600">Message composer</p><h3 className="mt-1 text-2xl font-semibold">New {pretty(view)}</h3></div><button onClick={onClose} className="text-2xl text-gray-400">×</button></div><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-medium">Audience<select name="audience" className="mt-1.5 w-full rounded-xl border px-3 py-2.5"><option value="individual">Individual recipient</option>{view === "notification" && <><option value="all_customers">All customers</option><option value="all_sellers">All sellers</option></>}</select></label><label className="block text-sm font-medium">{config[view].recipient}<input name="recipient" required={view !== "notification"} type={view === "email" ? "email" : "text"} className="mt-1.5 w-full rounded-xl border px-3 py-2.5"/></label>{view !== "sms" && <label className="block text-sm font-medium">Title / subject<input name="title" required className="mt-1.5 w-full rounded-xl border px-3 py-2.5"/></label>}<label className="block text-sm font-medium">Message<textarea name="body" required maxLength={view === "sms" ? 480 : undefined} className="mt-1.5 min-h-40 w-full rounded-xl border p-3"/></label><label className="block text-sm font-medium">Schedule (optional)<input name="scheduled_at" type="datetime-local" className="mt-1.5 w-full rounded-xl border px-3 py-2.5"/></label><p className="rounded-xl bg-blue-50 p-3 text-xs text-blue-700">The message is saved first. Use “Send now” from its review panel to dispatch it and record the provider result.</p><button disabled={saving} className="w-full rounded-xl bg-[#111827] py-3 font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save message"}</button></form></aside></div> }
function Status({value}:{value:string}) { const tone = ["sent","delivered"].includes(value) ? "bg-green-50 text-green-700" : value === "failed" ? "bg-red-50 text-red-700" : value === "cancelled" ? "bg-gray-100 text-gray-600" : "bg-amber-50 text-amber-700"; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone}`}>{pretty(value)}</span>; }
